### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by bakins** [prometheus/statsd_exporter#100]
Since 0.4, the config file format has changed to YAML as well as several other features. I'm currently running a version close to master in production to ensure I can use histograms.

Is it time to do a 0.5 release?  What other things would we liked to be merged before then?  I'm happy to do the mechanics of a releases if we decide its time.

**Comment by matthiasr** [comment]
I agree, but I'd like to get at least #101 in before a release.

**Comment by bakins** [comment]
@matthiasr Any other things we want to merge before a release? I'll admit I'm being selfish as I'm about to do a new build at $DAYJOB and would like to base it on a release :)  I'm happy to do the work for a release.

**Comment by matthiasr** [comment]
No, let's do one. I didn't find the time yesterday to write a changelog. I
want to be very clear about the breaking changes, with concrete
instructions for users what they need to do. If you want to write that,
please do! Otherwise I'll try to get it done later today.

**Comment by bakins** [comment]
@matthiasr I can give it a try. Would this upgrade information go into CHANGELOG.md?

**Comment by matthiasr** [comment]
Yes. I'll then also copy that into the Github release and the mailing list
announcement.

**Comment by bakins** [comment]
I hacked this together rather quickly: https://github.com/bakins/statsd-exporter-convert - would that be helpful?

**Comment by matthiasr** [comment]
Yes! let's reference it (in addition to the manual explanation, so people
can understand what's going on)

**Comment by bakins** [comment]
Closed by #108
