### ISSUE TITLE
Reading long lines from TCP closes the connection

### ISSUE THREAD

**Issue by matthiasr** [prometheus/statsd_exporter#109]
When reading from TCP, we abort and close the connection if any line does not fit into the bufio.Reader buffer. This is really not necessary, and the standard library has higher-level methods to reliably read lines from a stream.

Any solution should make sure to process the _last_ line in the stream, even if it does not end in a newline.

**Comment by matthiasr** [comment]
I'm going to close this because apparently nobody is bothered by this. If you are, please comment here and open a PR!

**Comment by imriz** [comment]
@matthiasr I just encountered this I think :)
Sending from Logstash's statsd output plugin.
BTW, I get the long line no matter how high I set statsd.read-buffer

**Comment by imriz** [comment]
My root problem is probably due to https://github.com/reinh/statsd/issues/76

**Comment by matthiasr** [comment]
Oh interesting … but a different issue then. I'll make one

**Comment by matthiasr** [comment]
see #302
