### ISSUE TITLE
question to supported metric types

### ISSUE THREAD

**Issue by Arnold1** [prometheus/statsd_exporter#112]
hi,

do you currently support metric type Sets?
```
StatsD supports counting unique occurences of events between flushes, using a Set to store all occuring events.

uniques:765|s
If the count at flush is 0 then you can opt to send no metric at all for this set, by setting config.deleteSets.
```

spec:
https://github.com/etsy/statsd/blob/master/docs/metric_types.md

**Comment by matthiasr** [comment]
No, at the moment we don't.

How would you like to have them mapped to Prometheus metrics? Keep in mind that "flushes" are not really a thing with Prometheus and we have to account for multiple Prometheus servers scraping the same target concurrently.

**Comment by Arnold1** [comment]
i would like to send the number of valid and invalid records (data loaded from a file) of my spark process and send it to prometheus. every time the spark process runs i would like to have to see actual value of the valid and invalid records in a prometheus graph...
any idea how to achieve that?

**Comment by matthiasr** [comment]
Can you do the computation in Spark and just push the numbers as a gauge? If you don't need statsd itself, you could also consider the [pushgateway](https://github.com/prometheus/pushgateway).

In general, we try to keep Prometheus handling numbers, not logic, and to some degree that also applies to exporters. I think supporting sets if they are supported upstream is a valid feature, but I can't see yet how we can sensibly map them into the Prometheus collection model.

**Comment by Arnold1** [comment]
@matthiasr thanks for the info to use the pushgateway! this one can also be used for spark streaming jobs?

**Comment by matthiasr** [comment]
I'm not sure about streaming jobs. It probably depends on the client side support (although the protocol is simple enough to just implement from scratch).

The pushgateway is even simpler than the statsd exporter. It basically just takes metrics you send (push) and remembers them for you so Prometheus can scrape them.

If you are continuously processing records, I'd keep _counters_ of each, and only take the rate at query time (this is the Prometheus-safe version of "reset at flush", it works for multiple servers).

If this job is long-running, is there any way it can itself just open a port and serve the metrics? Pushing anything should really only be the last resort, as far as Prometheus is concerned.

**Comment by matthiasr** [comment]
(either itself, or using the JMX exporter?)

**Comment by Arnold1** [comment]
@matthiasr ok, but JMX exporter only pushes metrics you defined in the following file?
 $SPARK_HOME/conf/metrics.properties

so to push my own metric to pushgateway, i need to implement that protocol?

"If this job is long-running, is there any way it can itself just open a port and serve the metrics? Pushing anything should really only be the last resort, as far as Prometheus is concerned." ... what if the job is short running?

**Comment by matthiasr** [comment]
> what if the job is short running

yes, that's what the pushgateway is for. I was just asking.

> so to push my own metric to pushgateway, i need to implement that protocol?

The [java client](https://github.com/prometheus/client_java) may also be of help, but I don't know.


This has gotten pretty far away from the original feature request. At the moment, I don't see a sensible way to implement support for sets. If anyone has one, please make a new issue – in the meantime I'll close this one.

@Arnold1 for usage questions, please see [the community page](https://prometheus.io/community/).
