### ISSUE TITLE
Clarify comment about "native solution" long term in Readme

### ISSUE THREAD

**Issue by SamSaffron** [prometheus/statsd_exporter#125]
Readme says:

> We recommend this only as an intermediate solution and recommend switching to native Prometheus instrumentation in the long term.

I would like this somewhat clarified. For forking web servers such as Passenger, Unicorn and Puma in the Ruby ecosystem, requests are round robined between process forks. This means you have no simple way of sharing state between forks and thus have a hard time collating data for an exporter. 

In this kind of setup a solution like statsd_exporter seems reasonable as the alternatives are all similarly messy. Be it sharing a pipe between all forks or nmaping a file and so on. 

I think the Readme should clarify that this is a completely legitimate solution for specific use cases such as aggregation of data from forked processes that all share an HTTP listener.

**Comment by matthiasr** [comment]
I think @SuperQ was working on improving the Ruby client so that statsd is no longer necessary there?

**Comment by SuperQ** [comment]
Yes, we have a working mmap-based multiproc Ruby client gem.  It needs a little more testing and to be merged upstream.

**Comment by matthiasr** [comment]
@SamSaffron in light of that, I would like to keep the README as it is – it still is a temporary solution, even if it's been a long temporary.

**Comment by SamSaffron** [comment]
Keep in mind this nmap solution has some serious limitations which is why it has not been merged, especially in pathologic cases where forked processes are crashing. 

We ended up building https://github.com/discourse/prometheus_exporter but essentially it ends up being a solution that is similar enough to statsd_exporter that I just don't feel it is justified saying "temporary" for statsd. Sure prom exporter is more flexible, but statsd exporter is also fine, and if implemented somewhere I would not be knocking on anyones door to migrate to ruby prom exporter.  

There are other forking servers out there that are not Ruby and forwarding metrics to a central collector on the box is a reasonable solution.

**Comment by SuperQ** [comment]
Our mmap solution does not suffer from those problems.   The reason it hasn't been merged are unrelated.

**Comment by SamSaffron** [comment]
@SuperQ  Good to hear but there are going to be certain levels of pain especially since this is not something that ships with Ruby, so you need a native extension, it will obviously not work in Windows and jRuby is going to need special care. 

Originally I built my exporter with IO.pipe which got shared via master process, but as time went by the isolation of having the collection in a dedicated process just became far more appealing then having these metrics floating around in my application server.

**Comment by matthiasr** [comment]
That is true, but in that case such an out-of-process proxy should really
not use a completely different data model than the Prometheus metrics you
actually want to collect.

**Comment by SamSaffron** [comment]
I think that is a totally legit point a collector that was designed from the ground up without needing to worry about statsd quirks would be better. You could batch metrics better, avoid the messy regex and other bonuses.
