### ISSUE TITLE
How to identify stale data?

### ISSUE THREAD

**Issue by InKolev** [prometheus/statsd_exporter#129]
Hi, I see that after I **stopped sending** a given metric **"X"** to statsd for **more than 30 minutes now**,  the **metric still appears in the export (/metrics) page** with its last set value.

I want the statsd_exporter to **stop reporting this metric** after it was stale for a given time.

What is the expected behavior in such cases? 
When will the metric stop being reported?
Is there a way to configure such timers?

Thanks in advance.

**Comment by matthiasr** [comment]
At the moment, there is no way to expire it except by restarting the exporter. I am hesitant to add the complexity of handling expiration; The Prometheus Way™ is to tie the lifecycle of metrics to that of the application – for the statsd exporter that means an instance of the exporter alongside each application instance, restarted together.

**Comment by xkisu** [comment]
I experienced the same thing and originally thought it was a bug, not the intended operation. Restarting the exporter in a container environment is simple enough, but what about when it's running on a VPS with other services on the same VPS feeding it metrics that need to restart from time to time?

It would be nice if there was at least an optional flag to set a timeout to mark a metric as stale.

**Comment by matthiasr** [comment]
Should this be global or per-metric?

**Comment by matthiasr** [comment]
(or rather, per-mapping)

**Comment by xkisu** [comment]
I was thinking global as that's how it would best apply to most of the use cases I'm thinking about, but I can see how per-metric could be useful too

**Comment by matthiasr** [comment]
Makes sense. We can probably start global and see if that solves the issues. So if anyone wants to implement this, please comment here and submit a PR!

**Comment by brian-brazil** [comment]
I'm not sure that's going to solve anything - if anything it'll just cause more problems. A metric is still valid even if it hasn't been updated in a long time - e.g. process_start_time_seconds.

**Comment by brian-brazil** [comment]
It's not a problem if the standard architecture is followed with the exporter matching the lifecycle of the thing that's exporting to it. This suggestion violates https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics

**Comment by matthiasr** [comment]
In a *Prometheus* "standard architecture", you don't need this exporter.

I see the purpose of this as providing a bridge between applications instrumented for a *statsd/graphite* standard architecture to metrics collection in Prometheus. These applications do not, semantically, follow the Prometheus instrumentation model, so if they emit a process start time, they will do so continuously, because that's what you need to do to get a continuous line in Graphite. Whether it's a gauge or not has no impact on this at all.

**Comment by brian-brazil** [comment]
Statsd works with a mix of both events and metrics, and it's the role of the statsd exporter to translate that into the Prometheus data model. This includes the idea that the only time you ever drop metrics is when the reporting process restarts.

What you propose will break slow moving counters for example.

**Comment by matthiasr** [comment]
You're right, statsd actually keeps the metrics alive, however it also has an interface to selectively expire them. I really would rather not implement _that_ but I think we need a solution for people integrating with a standard statsd setup, and that means a central statsd server that all services send to. Ideally, one would first introduce local statsd forwarders, but that means touching every single producer. I want to leave the door open to users who don't want to invest all that upfront before they get the first useful metric in Prometheus. I think expiry of metrics after some (user-chosen) interval is a good middle ground if it's opt-in. I am confident that we can document the tradeoffs and edge cases, as well as (better) alternatives.

**Comment by brian-brazil** [comment]
I can see where you're coming from.

**Comment by vinhlh** [comment]
How about marking metrics stale if they are scraped by Prometheus already. Then flush interval (same term in statsd) will be decided by Prometheus.
(Yep, some tradeoffs like Prometheus doesn't really scrape successfully but they are cleaned already).

**Comment by brian-brazil** [comment]
That would break multiple Prometheus servers scraping the same target.

**Comment by matthiasr** [comment]
This is now implemented in version 0.9.0.

**Comment by calebtote** [comment]
Is there a commit id we can look at?

**Comment by matthiasr** [comment]
The PR is https://github.com/prometheus/statsd_exporter/pull/164

**Comment by Upanshu11** [comment]
As far as I can see, this configuration is on a global level. Was anything similar done on a metric level as well?
