### ISSUE TITLE
Rename to statsd_exporter

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/statsd_exporter#13]
To be consistent with the rest of our exporters, this repository should be renamed to the statsd_exporter as it takes in data from a non-prometheus system and exports it in a prometheus format.

By contrast a "bridge" would take data in some prometheus format, and output it in a non-prometheus format.

**Comment by juliusv** [comment]
:+1:

**Comment by beorn7** [comment]
My thoughts, too.

**Comment by brian-brazil** [comment]
We still need to rename the repo.
