### ISSUE TITLE
Change default port to 8215

### ISSUE THREAD

**Issue by coopr** [prometheus/statsd_exporter#131]
I am under the impression that StatsD [default port is 8125](https://www.google.com/search?q=statsd+default+port) - as such, I'd suggest that the StatsD Exporter also default to 8125, rather than the current 9125

**Comment by matthiasr** [comment]
I would rather not do that. We try to [avoid port collisions](https://github.com/prometheus/prometheus/wiki/Default-port-allocations) and running classic statsd and the exporter side-by-side is a fairly common pattern, especially for a gradual migration. I understand that this means extra configuration to be a "drop in" replacement, but I'd rather have that explicitness than let new users run into port conflicts. Does that make sense @coopr?
