### ISSUE TITLE
missing debug parameter

### ISSUE THREAD

**Issue by Grummfy** [prometheus/statsd_exporter#132]
Hello,
I think the --log.level should be added to the tool, so it's hard to debug stuff in case of issue ;)

thanks

**Comment by matthiasr** [comment]
You're right, this should be exposed. If anyone wants to tackle this, please do 😃

**Comment by matthiasr** [comment]
Actually, this is a duplicate of #111 – it's not completely straightforward because the log package uses a different package than the exporter. I'll close this issue since there is more information over there.
