### ISSUE TITLE
Statsd exporter docker container exits with return code 2 on SIGTERM exit

### ISSUE THREAD

**Issue by jkemp101** [prometheus/statsd_exporter#133]
The container exits with an exit code of `2` when the container is stopped with a SIGTERM.  The exit code should be `143` or maybe `0` but not `2` which indicates an error occurred.  The process seems to exit with the right code so it might be something with the underlying docker image.

**Comment by matthiasr** [comment]
Could you expand on "the process seems to exit with the right code"? How did you determine this? How can a container exit with a different code than the only process within it?

**Comment by jkemp101** [comment]
@matthiasr The following is how I tested.  I think I also tested other `prom` images and they had the same behavior.  So I should probably close this issue and open one in the base image repo.  But I really haven't had time to dig into this to figure out what is happening.

To see the `2` exit code do something like this:
1. Run this in one terminal: `docker run --name statsd_test prom/statsd-exporter; echo $?`
2. Run this in a second terminal: `docker stop statsd_test`
3. The echoed output for the docker run command in step 1 will be `2`

To see the proper `143` exit code by the process:
1. Run: `docker run --name statsd_test --entrypoint sh  prom/statsd-exporter  -c 'statsd_exporter; echo $?'`
2. In second terminal run: `docker exec statsd_test killall statsd_exporter`
3. Output from echo should be `143` in first terminal.

**Comment by matthiasr** [comment]
Is the exit code of `docker run` the exit code of the container under all
circumstances? What exactly does `docker stop` do?

**Comment by jkemp101** [comment]
Here are the [docs](https://docs.docker.com/engine/reference/run/#exit-status) for the `docker run` command, it follows the `chroot` standard, `125`, `126`, `127`, or the exit code of contained process.  

Here are the [docs](https://docs.docker.com/engine/reference/commandline/stop/) on `docker stop`, it sends a `SIGTERM` and eventually a `SIGKILL` to PID 1 process.

**Comment by jkemp101** [comment]
I might be wrong about this but generally the `statsd_exporter` process should not be run as the init process (PID 1).  Instead it should be started by something like [https://github.com/krallin/tini](tini) which can do a better job of handling the responsibilities of being pid 1.  In fact, the latest versions of Docker have that built in, see [here](https://docs.docker.com/engine/reference/run/#specify-an-init-process).  

So in my tests if I run `docker run --name statsd_test --init prom/statsd-exporter` which uses the `--init` option I now get an exit code of `143` which is correct for a process exiting due to `SIGTERM`.  But I don't think I can use that docker option in Kubernetes so for now I build a custom image just to start `statsd-exporter` via `tini` to get the right exit codes.

**Comment by matthiasr** [comment]
I'm not sure if we should do this inside the docker image though, especially since the container runtime is picking up that responsibility?

> the responsibilities of being pid 1

Aside from reaping zombies, what are those? `statsd_exporter` does not start subprocesses (I think?)

> I now get an exit code of 143

is that the exit code of the init process now?

I'm still wondering what exactly is happening that produces this error code 2. _something_ must be emitting it?

**Comment by jkemp101** [comment]
Had a little time to play a little more with this.  Didn't get to the underlying cause but this is probably related to the default handling of SIGTERM by Go executables and the fact that this process is acting as the init process which as I mentioned has some peculiarities to it.

I think the issue would go away if the exporter installed a signal handler for SIGTERM and exited cleanly when receiving that signal.  I tested the node-exporter which doesn't have a signal handler and it does the same thing exiting with a code 2.  But Prometheus and alertmanager exit with a code 0 and they happen to install signal handlers [here](https://github.com/prometheus/prometheus/blob/68e8b80ffe5f7271861034c92125a3aefee992f8/cmd/prometheus/main.go#L370) and [here](https://github.com/prometheus/alertmanager/blob/3735df3ac7ffc290f134b974d622a9cfe97374c4/cmd/alertmanager/main.go#L405).

**Comment by matthiasr** [comment]
Ah that makes sense. Adding a signal handler seems easy enough. On the other hand, it _is_ additional code and complexity. So I'd like to ask: what issues is the current behavior causing, aside from aesthetics? Who benefits from changing the default?

**Comment by matthiasr** [comment]
And thank you for looking into it!

**Comment by jkemp101** [comment]
I use Prometheus to generate alerts for any k8s pod that exits with a code != to `0` or `143` since that signifies an error occurred.  This required me to build our own statsd image that uses [tini](https://github.com/krallin/tini) to avoid firing these alerts for normal deployments that run the statsd exporter as a sidecar.

I just created an issue for the Prometheus base image to see if that is an alternative fix.

I was curious why I see different behavior depending on how it is being run (command line or as pid 1).  Two likely spots that might be where the `2` is coming from is [here](https://github.com/golang/go/blob/ead59f4bf368f13bbabea3f8a59f9f29ccdd3900/src/runtime/signal_unix.go#L444) or [here](https://github.com/golang/go/blob/ead59f4bf368f13bbabea3f8a59f9f29ccdd3900/src/runtime/signal_sighandler.go#L151).   The exit path probably looks different when the process is running as pid 1 versus just a normal process with a terminal attached.

**Comment by matthiasr** [comment]
That seems alert seems a bit broad to me, especially since Docker can just
restart failed containers.

I'll try to summarize where we are at:

* when running in a container as PID 1 the process exits with error code 2
on SIGTERM
* this is Go runtime behavior, not specific to the exporter
* an explicit handler would maybe work around it
* it doesn't happen when running with an init process
* which could be added to the busybox base image
* but you can also get the same result with `docker run --init`
* the process exits when asked, so this is somewhat cosmetic

Is this summary correct?

**Comment by jkemp101** [comment]
Feels like we are going in circles here a bit.  I'm not sure if I agree with all of that summary.  I definitely don't agree error handling is cosmetic.  We can discuss the merits of use cases all day long but this comes down to this image indicates an error when I stop it with `docker stop` using the defaults for the `docker run` command.  Please just clarify if the expected behavior of this image is to indicate an exit code of `2` when it exits without an error (using `docker` command defaults)?  If that is the expected behavior we can move on.  Or am I doing something wrong and there is an error that I should fix?

**Comment by matthiasr** [comment]
I'm not saying that exiting with an error code is desired behavior, but I am also not convinced that it's worth adding complexity to handle this.

**Comment by matthiasr** [comment]
I'm going to close this issue. After thinking about it for a while, I don't think the additional complexity is worth it. By now, Kubernetes also supports running containers under a common init when [using shared process namespaces](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/).
