### ISSUE TITLE
Full match

### ISSUE THREAD

**Issue by tukataka** [prometheus/statsd_exporter#138]
Hi!
Is it possible to find by full match. F.e. now i force to send stat with name "name_someanother", cause i can't match with only "name".
As i found in code it's impossible.
Can it be implementing ?

**Comment by matthiasr** [comment]
I'm not sure I understand what you are trying to achieve. You should be
able to match on the whole metric name, what is not working for you? Could
you please provide your mapping configuration, and a few of the statsd
metric names your application sends?
