### ISSUE TITLE
Cannot unmarshal statsd-exporter.conf

### ISSUE THREAD

**Issue by kolesoffac** [prometheus/statsd_exporter#146]
Hi,
I use https://werner-dijkerman.nl/2017/05/27/monitoring-consul-with-statsd-exporter-and-prometheus/, but i have error.

`level=fatal msg="Error loading config:yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `consul....` into main.metricMapper" source="main.go:193"
`

How can i decied it?

Thanks

**Comment by matthiasr** [comment]
Since that article was written, the configuration format has changed. Please refer to the [release notes](https://github.com/prometheus/statsd_exporter/blob/master/CHANGELOG.md#v050--2017-11-16) for instructions on converting the configuration.

**Comment by matthiasr** [comment]
(I'll also leave a comment under the article for everyone else who comes across it)
