### ISSUE TITLE
Docker hub image v0.7.0 returns "error: unexpected" for any options passed

### ISSUE THREAD

**Issue by geauxvirtual** [prometheus/statsd_exporter#147]
Trying to run the latest statsd_exporter docker image. If I start a container and pass no options, the container starts just fine. 

![good](https://user-images.githubusercontent.com/1395030/44693180-4a2b7100-aa1b-11e8-94e3-4540680d0976.JPG)

If I pass any options such as `--statsd.mapping-config=/path/to/config`, the container exits with error `statsd_exporter: error: unexpected --statsd.mapping-config=/path/to/config, try --help`.

![error1](https://user-images.githubusercontent.com/1395030/44693185-51eb1580-aa1b-11e8-99d4-164f439fc53b.JPG)

Even if I try `--help` I get the same error `statsd_exporter: error: unexpected --help, try --help`\

![error2](https://user-images.githubusercontent.com/1395030/44693199-662f1280-aa1b-11e8-9498-ff8a42237b98.JPG)

**Comment by matthiasr** [comment]
You are passing `--` before the flags – the new flags package is GNU-flag-ish, so it stops flag processing at that point:

```
$ docker run prom/statsd-exporter:latest --version
statsd_exporter, version 0.7.0 (branch: HEAD, revision: 82f75d3b9ad053751cc2a5fe869c321b64a47934)
  build user:       root@7f2341abdbf5
  build date:       20180822-07:50:52
  go version:       go1.10.3
$ docker run prom/statsd-exporter:latest -- --version
statsd_exporter: error: unexpected --version, try --help
```

This is correct, just drop the extra `--` and you'll be fine. Sorry about not documenting this more clearly.

**Comment by matthiasr** [comment]
I think this behavior is even POSIX-specified: see Guideline 10 of the [Utility Conventions](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html).

**Comment by matthiasr** [comment]
reopening to add a note to the README
