### ISSUE TITLE
go build fails with the missing packages

### ISSUE THREAD

**Issue by champashankar** [prometheus/statsd_exporter#151]
Hi,
I was trying to build statsd, getting the below error:
Did i miss any step. I tried with both go-1.9 and go-1.10. Both are having same issue

root@platcon5:/home/champa/statsd_exporter# go build
main.go:21:2: cannot find package "github.com/howeyc/fsnotify" in any of:
        /usr/lib/go-1.9/src/github.com/howeyc/fsnotify (from $GOROOT)
        /root/go/src/github.com/howeyc/fsnotify (from $GOPATH)
exporter.go:33:2: cannot find package "github.com/prometheus/statsd_exporter/pkg/mapper" in any of:
        /usr/lib/go-1.9/src/github.com/prometheus/statsd_exporter/pkg/mapper (from $GOROOT)
        /root/go/src/github.com/prometheus/statsd_exporter/pkg/mapper (from $GOPATH)
/root/go/src/github.com/prometheus/common/log/log.go:27:2: cannot find package "github.com/sirupsen/logrus" in any of:
        /usr/lib/go-1.9/src/github.com/sirupsen/logrus (from $GOROOT)
        /root/go/src/github.com/sirupsen/logrus (from $GOPATH)
/root/go/src/github.com/prometheus/common/log/log.go:28:2: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
        /usr/lib/go-1.9/src/gopkg.in/alecthomas/kingpin.v2 (from $GOROOT)
        /root/go/src/gopkg.in/alecthomas/kingpin.v2 (from $GOPATH)

**Comment by matthiasr** [comment]
Go is very particular about the layout of your workspace. You *must* clone this repository into `$GOPATH/src/github.com/prometheus/statsd_exporter`. If you do not set it, `GOPATH` is `$HOME/go`, check `go env` to verify that.
