### ISSUE TITLE
s390x changes in the new branch

### ISSUE THREAD

**Issue by champashankar** [prometheus/statsd_exporter#153]
We built statsd_exporter for the s390x platform. Introduced a new dockerfile.s390x and made platform check in the Makefile to pick up this new dockerfile.s390x. Is it possible to have these changes in this repo with a new branch.
If so, please let me know, I'll make a new branch and raise a PR.

Thanks,
Champa

**Comment by matthiasr** [comment]
Is this part of the S390x effort discussed on the developers mailing list?
I would much prefer if this could be solved generally, and without special
dockerfiles, than with architecture-specific setups.

**Comment by champashankar** [comment]
This is part of s390x changes but not the one which you referred to as the discussion over the developers mailing list.
We picked up this as part of ICP on S390x server and for most of the projects to support on s390x, we introduced a new dockerfile and makefile would check for the platform and pick up the corresponding dockerfile.
So if you wish you have these changes in a separate branch specifically for s390x, please let me know.

**Comment by matthiasr** [comment]
It seems that that discussion has not come to a clear conclusion yet. While
it's still open, I would rather not start to introduce special solutions
here.

**Comment by matthiasr** [comment]
It looks like the s390x support in promu is done, so I'd be happy to accept the necessary changes to build and release for it here. For completeness, would you also be willing to do the same changes to the graphite exporter and influxdb exporter?

**Comment by matthiasr** [comment]
we are now releasing s390x tarballs, and generally using the same setup as prometheus/prometheus for  releases, so I believe this is done. please speak up if there is anything missing.
