### ISSUE TITLE
Documentation issue: Docker run command is incorrect 

### ISSUE THREAD

**Issue by gbahrani** [prometheus/statsd_exporter#155]
Docker run command is specified as:

docker run -d -p 9102:9102 -p 9125:9125 -p 9125:9125/udp \
        -v $PWD/statsd_mapping.conf:/tmp/statsd_mapping.conf \
        prom/statsd-exporter -statsd.mapping-config=/tmp/statsd_mapping.conf

When I run docker with this command, I see following error in the logs:

statsd_exporter: error: unknown short flag '-s', try --help

Command should have '--' for statsd.mapping-config instead of '-'. So correct command is

docker run -d -p 9102:9102 -p 9125:9125 -p 9125:9125/udp \
        -v $PWD/statsd_mapping.conf:/tmp/statsd_mapping.conf \
        prom/statsd-exporter --statsd.mapping-config=/tmp/statsd_mapping.conf

**Comment by matthiasr** [comment]
You're right, and instead of .conf it should be .yml – could you please
send a PR?

**Comment by gbahrani** [comment]
I have raised PR #156.
