### ISSUE TITLE
Counter for dropped metrics

### ISSUE THREAD

**Issue by filippog** [prometheus/statsd_exporter#160]
Hi,
To avoid polluting Prometheus metrics with unmapped statsd metrics I'm currently dropping everything that's unknown. Though how to handle cases where the application has added new metrics and those will need mappings? One potential solution I think is to expose (one? many?) counter(s) to count metrics that result in action `drop`, this way it is possible to monitor if additional metrics start being dropped. What do you think?

**Comment by matthiasr** [comment]
This sounds great! Should there also be a metric for events that fell off the end and ended up in an autogenerated metric?

**Comment by grobie** [comment]
Iirc we have an unmapped metric counter already.

**Comment by filippog** [comment]
Thanks for the quick replies!

Indeed @matthiasr that's what I would need. @grobie the `eventsUnmapped` counter was added in 3d0ccb9 but isn't registered with the collector afaics :( But yeah that's what I'm looking for, happy to send a PR along. 

Thoughts on adding a counter for dropped metrics?

**Comment by matthiasr** [comment]
`drop` is one of multiple actions. What other dimensions should we break down the count by?

**Comment by matthiasr** [comment]
Would this be an additional label on an existing metric, or a new one?

**Comment by filippog** [comment]
> Would this be an additional label on an existing metric, or a new one?

I'd imagine a new mapper-related metric with an `action` label, similar to `statsd_exporter_events_total` but broken down per action.

**Comment by matthiasr** [comment]
makes sense, do you want to send a PR?

**Comment by filippog** [comment]
> makes sense, do you want to send a PR?

Unlikely I'll find the time soon :(

**Comment by matthiasr** [comment]
done in #193
