### ISSUE TITLE
carriage return-terminated stats lines should be accepted

### ISSUE THREAD

**Issue by mfischer90** [prometheus/statsd_exporter#167]
Summary:

statsd exporter is not accepting stats lines that terminate in a `\r` character. At least some statsd implementations (notably [gostatsd](https://github.com/atlassian/gostatsd) do, and we should be compatible with that.

===========

I've installed statsd and the exporter on a centos 7 host, but the exporter is denying my metrics. 

Sending like this:
`echo "test:1|c" | nc -C -w1 -u 127.0.0.1 8125`

gets through statsd:
`TIME HOSTNAME node[22232]: TIME - DEBUG: test:1|h`

error on exporter:
`TIME HOSTNAME statsd_exporter[22702]: time="TIME" level=debug msg="Error building event on line test:1|h\r: Bad stat type h\r" source="exporter.go:535"`

I understand why the metric is being rejected, but at no point am I adding the carriage return. I'm unable to determine whether it's a distro quirk or something with statsd itself.

**Comment by mfischer90** [comment]
Statsd config:
`{
	backends: [ "./backends/repeater" ]
	, repeater: [ { host: 'localhost', port: 9125 } ],
  debug: true,
  dumpMessages: true
}`

**Comment by mfischer90** [comment]
figured it out, the -C was causing the \r to be added

**Comment by matthiasr** [comment]
Does statsd accept this message? If so, then the exporter should too.

**Comment by mfischer90** [comment]
@matthiasr I believe it does. For gostatsd at least. Doesn't seem it would be too hard for statsd_exporter exporter to handle this case

**Comment by matthiasr** [comment]
thanks! I've reopened and edited the issue accordingly.

**Comment by matthiasr** [comment]
Since there has been no further interest in the last 1.5 years, I am going to close this issue to declutter the backlog. If you have a need for this, please comment here, I am willing to accept this if someone needs it enough to make a PR!
