### ISSUE TITLE
staticcheck / go module issues with golang/circleci:1.11

### ISSUE THREAD

**Issue by matthiasr** [prometheus/statsd_exporter#173]
https://circleci.com/gh/prometheus/statsd_exporter/347#artifacts/containers/0

I can reproduce this locally (on macOS, using https://github.com/dziemba/mobymac) with the golang/circleci:1.11 image but not the golang:1.11.4 image or on Darwin directly.

For now, I'm cutting out staticcheck from the build to unblock the 0.9.0 release candidate.

**Comment by matthiasr** [comment]
@simonpasquier do you have any idea what these messages mean? is there anything I can do to make staticcheck go again?

**Comment by simonpasquier** [comment]
This is a weird error, looking into it.

**Comment by matthiasr** [comment]
No rush – CircleCI also seems to have issues talking to Quay.io so I can't cut a release right now anyway.

**Comment by matthiasr** [comment]
According to https://github.com/golang/go/issues/24661 staticcheck is not go modules ready yet
