### ISSUE TITLE
Allow metrics with inconsistent label dimensions

### ISSUE THREAD

**Issue by vsakhart** [prometheus/statsd_exporter#179]
Hello,

Currently if you try to update a metric with a labelset that is inconsistent with whats registered, the metric gets dropped. As of release [0.9](https://github.com/prometheus/client_golang/releases/tag/v0.9.0) of the Prometheus Go client, specifically [417](https://github.com/prometheus/client_golang/pull/417), inconsistent label dimensions are now allowed. 

One way to mitigate this issue is to restart the exporter on code changes but the exporter will still drop metrics if two different code paths try to update a metric with different label dimensions. Ideally the statsd exporter can handle this case and doesn't drop any metrics.

**Comment by matthiasr** [comment]
I agree, since it's officially allowed now we should support it. I'm going to close this issue and add the information to #114, since that has more history.
