### ISSUE TITLE
how to reload config file without stopping statsd_exporter?

### ISSUE THREAD

**Issue by katty0924** [prometheus/statsd_exporter#180]
Summary:
sometimes i want to reload the statsd_mapping.yml without stopping the statsd_exporter, when i update statsd_mapping.yml ,  because when  statsd_exporter stopped, the granfana will display no value.
Just like prometheus, if i chnage the config files, i can use command KILL - HUP PID， without stopping prometheus.
thank you

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
