### ISSUE TITLE
Support for Unix domain sockets interface

### ISSUE THREAD

**Issue by mohag** [prometheus/statsd_exporter#189]
Statsd [supports a Unix domain socket interface](https://github.com/statsd/statsd/pull/564) (which can be used between containers with volumes).

Kong seems to have [added it to their version of statsd_exporter](https://docs.konghq.com/enterprise/0.34-x/vitals-prometheus-strategy/#statsd-exporter-with-unix-domain-socket) as well, but [their repo](https://github.com/kong/statsd_exporter) does not seem to contain the relevant code.

[DogStatsD also supports](https://docs.datadoghq.com/developers/dogstatsd/unix_socket/) this.

This would be nice to have in statsd_exporter as well. Currently the obvious way to do this involves running a statsd instance to feed the stats into statsd_exporter from a Unix domain socket. If this is implemented, compatibility with Kong's options for specifying the socket details might make sense.

**Comment by matthiasr** [comment]
This is a reasonable feature request – the easiest way would be if Kong were to submit their code. @subnetmarco is this something you would be willing to contribute?

**Comment by fffonion** [comment]
The reason for Kong's private fork is mainly to add the feature of "min/max" gauge, which is a stateful gauge that reset after scrape, to support Kong Vitals functionality. And the "reset" pattern is obviously anti Prometheus pattern, so we decided not push it to upstream. (Correct me if I'm wrong : ) )

The work of unix domain socket is done together with the performance research, which incubated the fsm mapper that got merged in upstream. Thanks @matthiasr for a detailed review! The domain socket itself, after some experienment, we found it not gaining notible performance increase. So it's not given much attention. Since now there's a need for that functionality, I'll organize a PR.

**Comment by SuperQ** [comment]
@fffonion Yes, the "reset" pattern is very much not something possible with Prometheus as it breaks badly if you have more than one Prometheus. Having multiple Prometheus for HA is a standard deployment pattern.

If you wanted a min/max, it's best to track all samples of a metric over a specific time period and decay them from the ring buffer. Similar to how the Prometheus Summary is implemented[0].

[0]: https://github.com/prometheus/client_golang/blob/master/prometheus/summary.go

**Comment by matthiasr** [comment]
@fffonion thank you for the context! I agree that min/max is not something to upstream.

@mohag considering the unix domain socket interface does not help with performance, do you think it's still necessary? What is your use case?

**Comment by SuperQ** [comment]
@matthiasr min/max might be an interesting feature proposal for `Summary` type.

**Comment by matthiasr** [comment]
True but also not what this issue is about, and it wouldn't be a change in this exporter at all 😃

**Comment by mohag** [comment]
@matthiasr My use case is mainly with Docker Swarm to allow access to `statsd_exporter` via a volume mount. Our code talking to statsd is currently aimed at dogstatsd and has UDP and unix socket support. Currently, the UDP code only works with an IPv4 address (too strict string validation, no lookup support), not with a hostname (which is needed to find the service within the swarm). (That code on our side should be fixed to allow for hostnames, but the volume mounts that Unix sockets allows seems useful)

**Comment by matthiasr** [comment]
Hmm, over-zealous validation on the UDP sending side seems like a bad reason to add another whole mechanism to the exporter to be honest.

I'm not familiar with Swarm – could you put the exporter and the application into the same network namespace (Kubernetes-pod-like) and then UDP to 127.0.0.1?

**Comment by mohag** [comment]
@matthiasr I would prefer phrasing it as "enhanced DogStatsD and statsd compatibility" ;) (The UDP code is mostly in that state due to it being unused due to Unix socket support in Dogstatsd previously)

The main method of doing that seems to be to run the "service" (Swarm service is basically a Deployment (if set as replicated, or a DaemonSet of set as global) + Service, but only one container) in the host's network namespace. I'm not aware of a method to share a network namespace other than the host one (There are [some interesting hacks](https://github.com/rycus86/podlike) though).

**Comment by matthiasr** [comment]
alright, 👍 for adding socket support then. I think this should be behind a flag and off by default, since we haven't been doing it so far.

**Comment by JustinTArthur** [comment]
Adding my 👍. This opens the door to more security options in an execution environment. A bonus would be support for null-prefixed abstract socket paths, which don't have the same security benefits, but can exhibit even higher performance than filesystem-pathed unix sockets.

**Comment by mohag** [comment]
It works in initial testing, thanks! (I'm leaving it open in case there is some other criteria to close, you are welcome to close it)

**Comment by matthiasr** [comment]
ah no, I just forgot to close this after merging. thanks for following up!
