### ISSUE TITLE
Default timer type is undefined

### ISSUE THREAD

**Issue by ckoehn** [prometheus/statsd_exporter#195]
According to the readme the default timer type is a `summary`. But starting the `statsd_exporter` (version: 0.9.0) without any `statsd.mapping-config` creates just the `_sum` and `_count` time series for a `timer`.

#### Steps to reproduce

* `./statsd_exporter`
* `echo "foo:1234|ms|#one:1,#two:2" | nc -u localhost 9125`
* Check http://localhost:9102/metrics

#### Output
```
foo_sum{one="1",two="2"} 1.234
foo_count{one="1",two="2"} 1
```

#### Expected output
```
foo{one="1",two="2",quantile="0.5"} 1.234
foo{one="1",two="2",quantile="0.9"} 1.234
foo{one="1",two="2",quantile="0.99"} 1.234
foo_sum{one="1",two="2"} 1.234
foo_count{one="1",two="2"} 1
```

I get the expected output by specifying a minimal `mapping-config`: 
```yml
defaults:
  timer_type: summary
```

**Comment by matthiasr** [comment]
Interesting, that should not happen … but I'm wondering if this isn't our chance to move forward and make the default histograms.

**Comment by vsakhart** [comment]
I was just hit by this issue. This bug comes after https://github.com/prometheus/statsd_exporter/pull/135 where it expects a mapper to exist.

A simple fix would be to define the quantiles if they're empty to the previous default values used. @matthiasr Does that solution sound good to you? If yes, I can make a PR.

**Comment by vsakhart** [comment]
Alternatively, we could make defaultQuantiles in pkg/mapper/mapper.go a global variable and use it in this declaration 

https://github.com/prometheus/statsd_exporter/blob/4d0cb1992d3ee7930ebd3f1024ed0856465a5b1f/exporter.go#L184

**Comment by matthiasr** [comment]
Yes using the usual defaults (0.5, 0.9, 0.99) sounds good!

`c.mapper.Defaults.Quantiles` can be set by in the defaults section of the mapping config, we need to honor that.
