### ISSUE TITLE
Mapped metric name cannot be dynamic

### ISSUE THREAD

**Issue by sciffer** [prometheus/statsd_exporter#20]
When I tried taking parts of the parsed output and use it for the metric name, for example: "name": "$2_$3", it seems that statsd_bridge fail to start if I configure it and complains about it.
Using a static name it works.

**Comment by juliusv** [comment]
Yes, the metric name currently doesn't support this kind of templating, only the other labels. IMO the whole mapper is ripe for a complete overhaul, see also https://github.com/prometheus/statsd_bridge/issues/19.

**Comment by lswith** [comment]
any updates on this?

**Comment by drawks** [comment]
This limitation is a pretty big blocker preventing statsd_exporter from being a good drop in to get prometheus migration moving along. I imagine I'm not the only person in a shop that has many statsd metrics across many services across many groups of developers which would make writing and maintaining static config from this exporter a near toss up to the complexity of just doing native prometheus instrumentation/exporter for each app.

I can't speak for anyone else's use case, but being able to dynamically name metrics based on capture groups from the statsd names would make the first taste of prometheus from statsd a lot more palatable for our developers.

**Comment by PabloL007** [comment]
Is there any estimate on when this will be available?

**Comment by matthiasr** [comment]
This issue is duplicated by #62, but the discussion there has more detail. I'm going to close this one so we can keep the conversations focused.
