### ISSUE TITLE
Don't run docker container as root

### ISSUE THREAD

**Issue by der-eismann** [prometheus/statsd_exporter#201]
IMHO it is accepted as best practice to not run [processes in containers as root](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b). It is a problem that is affecting many of prometheus' exporters and I'm not sure if this was discussed before. 
It can be fixed pretty easily by adding two lines to the Dockerfile:
```
RUN adduser -D statsd-exporter
USER statsd-exporter
```

**Comment by SuperQ** [comment]
We typically use `nobody` for our containers.

**Comment by der-eismann** [comment]
I've seen this [in some containers](https://github.com/search?q=org%3Aprometheus+nobody&type=Code) (prometheus, alertmanager, node-exporter, pushgateway, prom2json) , but I think it isn't everywhere yet:
```
$ docker run --entrypoint /bin/whoami prom/statsd-exporter
root
```
It would be great if you could start adapting it in the other containers as well.
