### ISSUE TITLE
Not able to view the statsd metrics in prometheus

### ISSUE THREAD

**Issue by litgupta** [prometheus/statsd_exporter#215]
Hello,
I am using the following command to start statsd_exporter

` ./statsd_exporter --web.listen-address=":9102"  --statsd.mapping-config=config.yml --statsd.listen-tcp=":8125"`

My mapping configuration is as follows

`mappings:
 - match : TestApp.indexTimer
   timer_type: summary
   name: "my_timer"
   labels:
    provider: "indexTimer"
    job: "indexTimer_server"
   quantiles:
    - quantile: 0.99
      error: 0.001
    - quantile: 0.95
      error: 0.01
    - quantile: 0.9
      error: 0.05
    - quantile: 0.5
      error: 0.005

 - match: TestApp.index_call
   name: "count_gauge"
   labels:
    provider: "index_call"
~
I am running the statsd client from python-flask app and statsd server is running on localhost:8125. 
I am able to view the statsd metrics on console(backend used for statsd) , but not on the prometheus query list.

This is what prometheus query list displays for statsd
![Screenshot (77)](https://user-images.githubusercontent.com/22391215/57759409-858bde00-7717-11e9-99cc-e6a7ab891283.png)

What am I doing wrong ?

`

**Comment by matthiasr** [comment]
Hi, usage questions are better asked in our [community channels](http://prometheus.io/community).

With `name: "my_timer"` you are setting the desired metric name to `my_timer` – metrics received by the exporter do not get a `statsd_` prefix, only those of the exporter itself do.

In general, if you're unsure what exactly is being exported, look at the metrics endpoint of the exporter (`http://localhost:9102/metrics` by default).
