### ISSUE TITLE
Metrics received from the UDP listener are incorrectly formed in v0.10.3

### ISSUE THREAD

**Issue by yosida95** [prometheus/statsd_exporter#220]
After upgrading to v0.10.3, statsd_exporter starts exposing many junk metrics like the following snippet. 
```
# HELP uwsgi_core_avg_resp Metric autogenerated by statsd_exporter.
# TYPE uwsgi_core_avg_resp counter
uwsgi_core_avg_resp 4.827028e+06
# HELP uwsgi_core_avg_respo Metric autogenerated by statsd_exporter.
# TYPE uwsgi_core_avg_respo gauge
uwsgi_core_avg_respo 0
# HELP uwsgi_core_avg_response Metric autogenerated by statsd_exporter.
# TYPE uwsgi_core_avg_response counter
uwsgi_core_avg_response 901008
# HELP uwsgi_core_avg_response_time Metric autogenerated by statsd_exporter.
# TYPE uwsgi_core_avg_response_time gauge
uwsgi_core_avg_response_time 234898
# HELP uwsgi_core_avg_response_time_ Metric autogenerated by statsd_exporter.
# TYPE uwsgi_core_avg_response_time_ counter
uwsgi_core_avg_response_time_ 3061
# HELP uwsgi_core_avg_response_time_1 Metric autogenerated by statsd_exporter.
# TYPE uwsgi_core_avg_response_time_1 counter
uwsgi_core_avg_response_time_1 1261
# HELP uwsgi_core_avg_response_time_167 Metric autogenerated by statsd_exporter.
# TYPE uwsgi_core_avg_response_time_167 counter
uwsgi_core_avg_response_time_167 0
# HELP uwsgi_core_avg_response_time_1670 Metric autogenerated by statsd_exporter.
# TYPE uwsgi_core_avg_response_time_1670 counter
uwsgi_core_avg_response_time_1670 0
# HELP uwsgi_core_avg_response_time_16705 Metric autogenerated by statsd_exporter.
# TYPE uwsgi_core_avg_response_time_16705 counter
uwsgi_core_avg_response_time_16705 0
# HELP uwsgi_core_avg_response_time_167055_g Metric autogenerated by statsd_exporter.
# TYPE uwsgi_core_avg_response_time_167055_g counter
uwsgi_core_avg_response_time_167055_g 0
# HELP uwsgi_core_avg_response_time_167055_gsts Metric autogenerated by statsd_exporter.
# TYPE uwsgi_core_avg_response_time_167055_gsts counter
uwsgi_core_avg_response_time_167055_gsts 0
```

In my investigation, it seems due to a buffer overwrite during receiving packets. and it was introduced in  4cf6f74dc321ec5afde5bfd5954c873421cae6e0.

1. Receive a UDP packet into the buffer. (https://github.com/prometheus/statsd_exporter/blob/4cf6f74dc321ec5afde5bfd5954c873421cae6e0/exporter.go#L823-L825)
2. Parsing it and produce Events to the channel *with no copy*. (https://github.com/prometheus/statsd_exporter/blob/4cf6f74dc321ec5afde5bfd5954c873421cae6e0/exporter.go#L846-L861)
3. The next UDP packet arrived and it overwrites the buffer.
4. The event handler receives an event sent by 2 and registers it with *modified name* as underlaying memory was overwritten by 3. 

I have deployed my custom v0.10.3 build with 4cf6f74dc321ec5afde5bfd5954c873421cae6e0 reverted, and confirmed it fixes this issue.

**Comment by gaizeror** [comment]
Happens to us too

**Comment by matthiasr** [comment]
Thank you for the report and the thorough investigation. I'm going to revert #218 for now. @claytono since you're most familiar with this, could you take a look at ways to fix the race condition?

**Comment by matthiasr** [comment]
Reopening this to track bringing back #218

**Comment by claytono** [comment]
@matthiasr I'll take a look at this today

**Comment by claytono** [comment]
@matthiasr I think it makes sense to close this out right now and leave the revert in place.  If it makes sense to revisit this later, then we'd probably want to include it into a larger patch that batches events when sending on the channel.  If we do that, we'd probably want to change how memory management for this packet buffer works anyway.

**Comment by matthiasr** [comment]
Alles klar, thank you for following up!
