### ISSUE TITLE
Split into reusable packages

### ISSUE THREAD

**Issue by Gollam** [prometheus/statsd_exporter#234]
There are some useful structs and functions in the exporter.go file, which I'd like to reuse in my project. But I cannot import the file this way, because it is part of the main package. Can you please move it to some other package?

**Comment by matthiasr** [comment]
Yes, I think this is a really good idea, I have been thinking about this as well.

I am also maintaining the [graphite exporter](https://github.com/prometheus/graphite_exporter). The two do almost _exactly_ the same, the only difference is the parsing of the metric lines – alas, the code has diverged so much that they are almost completely different. The statsd exporter is much more advanced and has had many performance improvements, so it could be the basis for both.

Specifically, the bits that I would like to see extracted are:

* listening on ports and handling the stream(s) of line-wise input
* statsd metric line parsing from `[]byte` to a statsd-semantics event (dot-style metric-name + label/value pairs + type)
* the mapping from statsd-semantics events to prometheus metrics is already extracted and reused
* the registry, with expiration + metrics exposition

With this, the main package should only consist of plugging these together, and then the graphite exporter could do the same except plug in a different line parser.

What is your use case? Which bits would you need exported?

**Comment by Gollam** [comment]
Mainly, what I need is the escapeMetricName and lineToEvents functions, and of course the related structs. With those, I could skip writing a parser for the protocol.

**Comment by matthiasr** [comment]
Hmm, I am wondering if escapeMetricName should be part of the mapping logic, since it's essentially the fallback mapping mechanism.

**Comment by matthiasr** [comment]
Done in #298
