### ISSUE TITLE
build docker images can't run 

### ISSUE THREAD

**Issue by rulai-zhuyi** [prometheus/statsd_exporter#238]
when docker run : docker run statsd-exporter:1.2.0
error:
standard_init_linux.go:207: exec user process caused "exec format error"

**Comment by matthiasr** [comment]
What platform is this on? How did you obtain this image? I cannot reproduce this issue when using the image from Docker Hub:

```
docker run prom/statsd-exporter:v0.11.2 --version
```

**Comment by rulai-zhuyi** [comment]
I was't use  Docker Hub image , Because of i need to change docker image's expose port ,So i build code and build image ,my platform is mac version 10.14.3.

**Comment by rulai-zhuyi** [comment]
cause is i  compiled the binary for Darwin,  not for base image platform linux

**Comment by matthiasr** [comment]
Thank you for the follow up!
