### ISSUE TITLE
Remove automatic configuration reloading

### ISSUE THREAD

**Issue by matthiasr** [prometheus/statsd_exporter#241]
The watch-based reloading was introduced a [long time ago](https://github.com/prometheus/statsd_exporter/commit/eff54bdcf928b2495faee465559bd94249253593). It blocks AIX support (#240) because it relies on an old version of the fsnotify library.

Hot reloading configuration causes a lot of complexity in properly rolling over the mapping infrastructure as the config changes. On the other hand, restarting the exporter is a quick thing, and Prometheus handles the counter resets.

I don't know of any other exporters that support hot reloads.

If you have a strong use case for hot configuration reloading, please speak up, otherwise I would be happy to accept a PR that rips it out.

**Comment by matthiasr** [comment]
@juliusv do you remember why you added it?

**Comment by brian-brazil** [comment]
> I don't know of any other exporters that support hot reloads.

The JMX exporter does, but that's because we can't presume to own SIGHUP as we're sharing a JVM with an application. Others like snmp, blackbox, and cloudwatch have the usual HUP/reload reloading.

**Comment by matthiasr** [comment]
I'm thinking about removing *all* ability to reload without restarting.
Would that be preposterous?

**Comment by brian-brazil** [comment]
Given the particular way this exporter works, I don't think it's unreasonable.

**Comment by juliusv** [comment]
> @juliusv do you remember why you added it?

@matthiasr I added it back then because the statsd exporter was one of the first (or *the* first?) exporters, and everything (including Prometheus) had file-watcher-based reloading back then. This was basically because we were used to that from Google :)

I think it's ok to take it out.

**Comment by juliusv** [comment]
(just that at Google, the watching happened via config in Chubby, not a local file)

**Comment by matthiasr** [comment]
thinking about this a bit more, I'm going to leave SIGHUP-triggered reloading in for now. I can see a few use cases (large shared statsd/exporter deployments) where restart-to-reload would be at least inconvenient. The issue at hand is with inotify, not with the reload complexity per se, so I don't need to make things more inconvenient than necessary right now.
