### ISSUE TITLE
Support single letter metrics

### ISSUE THREAD

**Issue by mizhka** [prometheus/statsd_exporter#256]
This issue is found inside graphite_exporter which use mapper for parsing YAML file. 
The official Apache JMeter provides metrics to Graphite with keys containing single letter as part of key (https://jmeter.apache.org/usermanual/realtime-results.html). 
For instance: \<rootMetricsPrefix\>\<samplerName\>.**h**.count
h - is single letter key part. 

With pre-yaml graphite_exporter, it's worked fine, but now it's issue due to parsing error:

```
$ ./graphite_exporter --graphite.mapping-strict-match --graphite.mapping-config=./mapping.config 
INFO[0000] Starting graphite_exporter (version=0.6.2, branch=HEAD, revision=32fbcbc7ef1316b35401927ce34daa6001accd5e)  source="main.go:245"
INFO[0000] Build context (go=go1.12.5, user=root@7a71ba4968b6, date=20190603-08:16:17)  source="main.go:246"
FATA[0000] Error loading metric mapping config: invalid match: p.*.*.c.*  source="main.go:256"
```

It means that patterns like "p.\*.\*.c.\*" are not supported now, but it's valid pattern. 

The regexp to validate this expression is inside pkg/mapper. 

Hope for your understanding

**Comment by matthiasr** [comment]
yes we should support those. can you send a PR?

**Comment by mizhka** [comment]
Hi @matthiasr ,

Is there any instruction how to send a PR? Thank you in advance

**Comment by matthiasr** [comment]
There are no special requirements except for the [certificate of origin](https://probot.github.io/apps/dco/). How to open a PR generally is [documented here](https://help.github.com/en/articles/creating-a-pull-request).
