### ISSUE TITLE
Values from statsd_exporter are divided by 10x

### ISSUE THREAD

**Issue by sveronese** [prometheus/statsd_exporter#258]
I'm facing an issue that I don't fully understand. I have a setup as following:

```
                 |--UDP--> STATSD -UDP-> GRAPHITE-BACKEND-1
                 |
APPLICATION -----|
                 |					              
                 |--UDP---> STATSD_EXPORTER <-| PROMETHEUS PULL                  
```
I'm doing tests using a counter metric. When I graph the value from prometheus and graphite for the same counter metric I have the same values except for the fact that values from STATSD are multiplied by 10x (and that STATSD is loosing data sometimes). I try to use ngrep in order to see the value that is sent to graphite from STATSD and I can confirm that the values are the same that I see in the graph so it seems that the data received by STATSD_EXPORTER are exposed to the api divided by a 10x factor. I'm using following formula to extract the data from prometheus:

```rate(business_driverposition{app="api-node",source="api-node"}[1m])```

The values sent from the application are in this format:

```production.api-node.positions.tasks.success:1|c```

I attached a screenshot for reference:

![Screenshot 2019-08-28 at 15 19 15](https://user-images.githubusercontent.com/1786652/63859636-08276900-c9a8-11e9-8432-042a02ac7db6.png)

I can't find anything in the documentation related to that. Do you have any idea why this is happening ? I'm maybe missing something ?

Thank you.

**Comment by matthiasr** [comment]
Hmm, good question. What is the Graphite query?

The default statsd flush interval / [recommended Graphite config](https://github.com/statsd/statsd/blob/master/docs/graphite.md) uses a 10-second interval. What statsd flushes to Graphite is the count per 10 seconds. On the other hand, Prometheus' `rate()` function always normalizes to 1s. My actual Graphite knowledge is vague, but I've gotten results in line with what I expect by using `scaleToSeconds(production.api-node.positions.tasks.success, 1)` in the past.

**Comment by sveronese** [comment]
@matthiasr Thank you very much for your reply. The flush interval of 10 seconds is what we have at the moment and the graphite query is plain query without any function. Your answer about the rate() that normalizes to 1s make totally sense for me and completely answer my question. What I was graphing with graphite plain query was the aggregation of point on 10s. Applying scaleToSeconds function to the graphite query give the same results.

Thank you very much for your help.
