### ISSUE TITLE
Confusing documentation regarding `use_ms`?

### ISSUE THREAD

**Issue by amitsaha** [prometheus/statsd_exporter#260]
Hi all, the README has this bit:

> The DogStatsD client by default emits timer metrics in seconds, set use_ms to True to fix this.

Is this correct?

Looking at the dogstatsd Python client, we have this code in [base.py](https://github.com/DataDog/datadogpy/blob/master/datadog/dogstatsd/base.py):

```
def timing(self, metric, value, tags=None, sample_rate=1):
        """
        Record a timing, optionally setting tags and a sample rate.
        >>> statsd.timing("query.response.time", 1234)
        """
        self._report(metric, 'ms', value, tags, sample_rate)
```
This is reporting the metrics in `ms`.

**Comment by matthiasr** [comment]
I'm not closely familiar with the dogstatsd client. The note was added in #254 – I'm happy to accept further improvements to it. The high-level version is that whichever client you use, it needs to behave like an _original_ statsd client, i.e. report timings in milliseconds.

It seems to me that `use_ms` is to be passed when initializing the `Dogstatsd` object? https://github.com/DataDog/datadogpy/blob/d87077662da8af9b74338a4b1b8a9a9b8d8d99ec/datadog/dogstatsd/base.py#L63

**Comment by amitsaha** [comment]
Thanks for the clarification @matthiasr - the `use_ms` argument only applies to the `timed()` decorator. (original [commit](https://github.com/DataDog/datadogpy/commit/7de341c78465220d42e5a073e12497580116dc28) in dogstatsd. 

Hope the PR looks sensible. Please take a look when you can.
