### ISSUE TITLE
Support SignalFX tagging style

### ISSUE THREAD

**Issue by matthiasr** [prometheus/statsd_exporter#268]
As a follow-up to #267 we should also support the [SignalFX dimension statsd extension](https://docs.signalfx.com/en/latest/integrations/agent/monitors/collectd-statsd.html#adding-dimensions-to-statsd-metrics).

See also statsd/statsd#619 for more discussion around tagging styles.

This tagging style is somewhat different from the ones we already support. At this point it would be good to break "generalized statsd parsing" out into its own package, and make sure it is well tested (and benchmarked – this is a very hot code path).

**Comment by matthiasr** [comment]
The second part (breaking this out into its own package) is done now, so this is easier than it used to be. Does anyone need it?

**Comment by glightfoot** [comment]
I'll take a whack at it
