### ISSUE TITLE
Switch logging to go-kit

### ISSUE THREAD

**Issue by matthiasr** [prometheus/statsd_exporter#270]
About two years ago we decided to move from logrus to go-kit for logging, this is one of the repos that still needs switching. prometheus/snmp_exporter#447 is an example PR.

**Comment by dedifferentiator** [comment]
@matthiasr I would like to try to resolve this

**Comment by mhartenbower** [comment]
@matthiasr I'll help out with this one

**Comment by matthiasr** [comment]
👍 go for it!
