### ISSUE TITLE
Metric mapping cache issue when variable uses in name

### ISSUE THREAD

**Issue by nikitka** [prometheus/statsd_exporter#273]
Hello,

I've found a issue with mapping cache when variable uses in name. Trivial example:

```
mappings:
  - match: aa.bb.*.*
    name: "aa_bb_${1}_total"
    labels:
      app: "$2"
```

```
echo "aa.bb.cc.myapp:1|c\naa.bb.cc.myapp:1|c\naa.bb.dd.myapp:1|c\naa.bb.cc.myapp:1|c\n" | nc -w 1 -u 127.0.0.1 9125 && curl -s http://127.0.0.1:9102/metrics|grep myapp
aa_bb_cc_total{app="myapp"} 2
aa_bb_dd_total{app="myapp"} 2
```

When cache disabled (via `statsd.cache-size=0`) I got expected results:

```
echo "aa.bb.cc.myapp:1|c\naa.bb.cc.myapp:1|c\naa.bb.dd.myapp:1|c\naa.bb.cc.myapp:1|c\n" | nc -w 1 -u 127.0.0.1 9125 && curl -s http://127.0.0.1:9102/metrics|grep myapp
aa_bb_cc_total{app="myapp"} 3
aa_bb_dd_total{app="myapp"} 1
```

If I understand correctly `FSM.GetMapping` returns the same mappingState pointer for `aa.bb.cc.myapp` and `aa.bb.dd.myapp`.  And before placing in the cache we update `Name` property for both metrics (because pointer is the same). I see solution with copying mappingState before placing in cache, but not sure of the correctness and I don't have Go language skills to make it perfectly. Could you fix this please?

**Comment by matthiasr** [comment]
Thank you for the report and the complete repro instructions!

**Comment by matthiasr** [comment]
@bakins is this something you could take a look at?
