### ISSUE TITLE
Log ingested metrics at debug level

### ISSUE THREAD

**Issue by calebwoofenden** [prometheus/statsd_exporter#299]
Hopefully this is an easy question to answer, I just haven't been able to figure it out.

How can I see all of the statsD metrics that are being sent to my exporter? Is it getting sent to a log file or anything? I want to see the statsD data being sent before it's exported to Prometheus format.

**Comment by matthiasr** [comment]
These should be logged at debug level, does that solve your problem?

**Comment by calebwoofenden** [comment]
@matthiasr I'm not seeing them. I have the statsd exporter running in a kube pod and I'm seeing the startup info log messages and a couple warning messages but no debug messages. I know that metrics are being sent to the statsd-exporter, since I see them coming out in prometheus format from the other end.

**Comment by matthiasr** [comment]
Debug logging is turned off by default because thus could be a huge volume.
You need to turn it on through a command line flag.

**Comment by calebwoofenden** [comment]
@matthiasr in the documentation I only see `--log.level` which says it defaults to `"info"`. Is this what you're referring to? Do I have to set it to `"debug"`? Wouldn't that cause `info` logs to be ignored?

**Comment by matthiasr** [comment]
Debug includes everything, just like info includes warnings

**Comment by atjeff** [comment]
Yeah man this isn't logging a single thing for me @matthiasr `./statsd_exporter --statsd.mapping-config=mappings.yml --log.level=debug --log.format=logfmt`

**Comment by calebwoofenden** [comment]
I'm also not seeing anything with `statsd_exporter --statsd.mapping-config=/statsd/statsd.yaml --log.level=debug`

**Comment by matthiasr** [comment]
oh interesting, I think I got confused with the [graphite exporter](https://github.com/prometheus/graphite_exporter) which does log every ingested line.

This is something we should add, can you make a PR?

**Comment by calebwoofenden** [comment]
It looks like the code is present to handle this argument: https://github.com/prometheus/statsd_exporter/blob/master/vendor/github.com/prometheus/common/log/log.go#L59

I'm unfamiliar with this codebase and have never developed in Go before, so I'm missing a lot of context here and would have a hard time debugging this. It might be a quick fix for someone more familiar with this code.

**Comment by snc43** [comment]
As I was running short of time, hence I add a debug log statement to https://github.com/prometheus/statsd_exporter/blob/37e54d0f473932bf360482a13077040451bb529d/exporter.go#L317 

`
level.Debug(logger).Log("msg", "Inbound UDP packet:", line)
`
