### ISSUE TITLE
Support for non-timer histograms?

### ISSUE THREAD

**Issue by jacknagel** [prometheus/statsd_exporter#307]
I'm working with a legacy application that emits StatsD metrics. Some of the metrics are histograms (i.e. 'h' type) and represent data like document page counts or request/response size. statsd-exporter assumes these are timers, and divides the values by 1000.

Is there any possibility this behavior can be made configurable?

**Comment by matthiasr** [comment]
The [statsd metrics page](https://github.com/statsd/statsd/blob/master/docs/metric_types.md) only lists the "ms" timers. I see that we already accept "h" as well, which I presume stands for histograms.

Which client are you using, and which server do you use as a reference? What is the line format that is sent in this case (the latest release will log this at `--log.level debug`)?

What I am thinking about is not making this configurable at all, but interpreting `ms` as scaled and `h` as unscaled. Would that suit your use case? It would be a breaking change that I want to document very clearly, so I want to understand exactly which setups this affects in what way.

**Comment by jacknagel** [comment]
The application is using the [node-statsd](https://github.com/sivy/node-statsd) client, and currently sends metrics to telegraf using the [statsd input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd), which are then sent to influxdb.

Here's some examples of what is sent:
```
Service.<service name>.Histogram.HttpRequestSize:155|h
Service.<service name>.Histogram.HttpRequestSize:123|h
Service.<service name>.Histogram.HttpResponseSize:1849|h
Service.<service name>.Histogram.HttpResponseSize:85229|h
Service.<service name>.Viewing.DocumentPageCount.xls:1|h
Service.<service name>.Viewing.DocumentPageCount.html:3|h
Service.<service name>.Viewing.DocumentPageCount.csv:1|h
Service.<service name>.Viewing.DocumentPageCount.docx:1|h
Service.<service name>.Viewing.DocumentPageCount.txt:1|h
```

> What I am thinking about is not making this configurable at all, but interpreting ms as scaled and h as unscaled. Would that suit your use case?

This would certainly work for us.

**Comment by matthiasr** [comment]
Thank you for the details! More for myself, references for treating histograms like timers without unit:

https://github.com/sivy/node-statsd
https://github.com/netdata/go-statsd
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd

**Comment by matthiasr** [comment]
Implementation note: currently, the division by 1000 (to convert from milliseconds to base units) happens [too](https://github.com/prometheus/statsd_exporter/blob/1f3adf69c691b3985fbaa341014e99ed669a541a/pkg/exporter/exporter.go#L156) [late](https://github.com/prometheus/statsd_exporter/blob/1f3adf69c691b3985fbaa341014e99ed669a541a/pkg/exporter/exporter.go#L166) to know how the event was submitted. This should be moved to [where we parse the event](https://github.com/prometheus/statsd_exporter/blob/1f3adf69c691b3985fbaa341014e99ed669a541a/pkg/line/line.go#L45) to make the distinction possible. That's a minor but subtle change to the interface of the line and exporter packages; we should call that out in the changelog.
