### ISSUE TITLE
Allow specification of histogram buckets from client

### ISSUE THREAD

**Issue by SpencerMalone** [prometheus/statsd_exporter#313]
Current there is an explicit mapping required when working with histograms. The exporter has to have predefined buckets mapped out for each incoming timer, which means that when adding new metrics to an application, you also have to edit the statsd exporter configuration. In the past this wasn't as troublesome for us, since you would always be doing that to regex out metric data like labels, but with the recent support for all the different dynamic label formats such as dogstatsd, suddenly the door is open for a world in which we have little to no static mappings in our statsd configuration. I'd love to continue down that path by allowing clients to specify their histogram buckets

My proposition:
Allow for dynamic data to be passed into the `buckets` option, or add a new `bucket_string` that is exploded into an array using a predefined label, or through some form of string interpolation. The largest limitation I see here is that you would have to reload/wipe metrics when conflicting bucket sets roll in, or dump a log saying that there was a conflicting dynamic bucket mapping and that it will continue using the first bucket mapping it found.

I'm willing to devote some time to this, but wanted to start with an issue to see what others thought about this problem and if anybody sees other potential solutions (or maybe one already exists and I am just dum?)

**Comment by matthiasr** [comment]
Hrmmm, I am not sure about this. Does any other statsd server implementation do this?

I want this exporter to be a way to bridge existing instrumentation into Prometheus, but I don't really want it to be a thing in itself. There is enough fragmentation in the statsd ecosystem already.

My policy for the line protocol so far has been to support (where feasible) what already exists in other server implementations, but not to make up anything new ourselves.

**Comment by glightfoot** [comment]
Thats understandable. I am not aware of any other instances that do this with statsd, but I would still argue that the first method (not creating a new metric type) would be very beneficial and backwards-compatible with all other statsd-client libs (that support tags). Statsd is still a good event protocol for metrics and this exporter is the best solution we have found for dealing with languages that don't have long-running processes. I think this would actually be closer to the functionality of the distribution (`d`) [dogstatsd metric type](https://docs.datadoghq.com/metrics/distributions/).

Having an optional convenience option to specify buckets from a label adds a significant amount of functionality and usability while still working within the statsd protocol (or at least all the extended tag protocols).

**Comment by SpencerMalone** [comment]
I definitely understand not wanting to add new unique functionality. How
about allowing string interpolation in histogram bucket definition? That
wouldn't be unique and is already something we support for some other
properties, but would allow us this new behavior. I don't think most statsd
backends have to think about histogram bucket definition, which may be why
there isn't an established pattern for this in the statsd ecosystem.

**Comment by matthiasr** [comment]
Can you give an example what that would look like?

You are right that the exporter / Prometheus integration are special
because it requires the bucket definition. Maybe this is worth supporting
after all … I'm not sure.

**Comment by brian-brazil** [comment]
Hmm, the other approaches work via quantiles rather than buckets. So equivalently the other approaches require the quantiles to be defined, and I've not ever come across a case where the ultimate end quantiles were chosen by the statsd client rather than the statsd.

**Comment by glightfoot** [comment]
What if we added an API for configuring mappings? This could be done outside of the statsd protocol and would allow implementations using the exporter to configure everything dynamically without using a config file, which would make using the exporter much simpler and a better user experience. It could be as simple as accepting the existing mapping config as a JSON post and logging an error if conflicting mappings are added subsequently

**Comment by matthiasr** [comment]
That's a really good idea, but does it have to be part of the exporter
itself? What would be needed to let a sidecar do this? We already support
reloading the mapping on SIGHUP.

**Comment by glightfoot** [comment]
I'm not sure that would work too well in practice. To ensure that the mapping is loaded before sending metrics from short running processes, you'd need to be sure that your mapping is added atomically. Having to make a REST request to a sidecar process that reads in the current config, manipulates it to add the new mapping, writes out a file and triggers a reload of the exporter is a complex pathway rife for errors. Additionally, this would take longer the more mappings are added. It seems very probable that a metric could be sent before the mapping is loaded and you end up with two metrics (one with the default config, and another later once the mapping is loaded).

I still think the most reliable solution would be accepting buckets/quantiles in a tag, but having a REST endpoint to configure mappings directly would still work and be much easier to reason around, as the call could block until the mapping is loaded.

We've been bitten by the default prometheus answer of "use a sidecar to write a file" before. It doesn't feel like a good user experience to have to develop a custom sidecar to write files to communicate between processes

**Comment by matthiasr** [comment]
I don't understand this use case. Are you trying to track individual
events? What meaning do the time series have if the distribution/buckets
change across instances of your short running process?

**Comment by SpencerMalone** [comment]
Sorry, we kind of fell off on this. Our use case is as follows:

We're using this exporter because PHP doesn't have a great solution for exporters due to it's lack of a central thread. We're working with a fairly legacy monolith, so there's a wide variety of metrics we are trying to export. Our PHP application is handling a variety of process models, from web requests to long running data pipelines to medium length cron-like tasks, which speaks to the variety of metrics and timeframes we are handling. The current workflow for deciding on buckets relies on having intricate knowledge of the metric pipeline. Our workflow for histograms is...
A) Write your code that ships statsd metrics out from the PHP application
B) Create the statsd exporter bucket definitions in the statsd exporter

All in all, not the _worst_, but it does mean that every engineer who wants to ship timing data needs to have decently in depth knowledge about the configuration of the statsd exporter application, which can get painful when you have hundreds of engineers who need to at some point do this.

Meanwhile, we have a growing collection of services that are based in languages that more natively support prometheus exporters and allow all of the definition of exported metrics to be done in the application itself. These applications have a much lower barrier to entry for adding metrics, and engineers are much happier to engage with exporting metrics.

We would like to bring our PHP metric exporting to be as similar to the models of the more strongly supported languages (aka golang) as we can manage, which led us to this idea: Specifying histogram buckets from the requester instead of the server.

**Comment by matthiasr** [comment]
Hmmmmm. I am unhappy that the statsd exporter seems to be "the way" for integrating PHP with Prometheus, and I would really rather not double down on that.
There are [PHP client libraries](https://github.com/promphp/prometheus_client_php) – while this one requires an external store (Redis) that's no worse than the situation with the exporter. In Ruby land there is a similar problem, I am not sure how transferable the solutions there are though.
I am going to have to say No to this – I think it is overstepping the bounds of the exporter's scope as I see it, and I would rather see the energy directed at improving the Prometheus-PHP ecosystem. Thank you for the deep discussion! I am always curious to know how the exporter is being used 😃

**Comment by matthiasr** [comment]
One more thought – the way we originally imagined the exporter to be used (and how we use it with our old Rails monolith) is to deploy it, conceptually, as part of the application. That means running it local to the node / as a sidecar in the pod; with the configuration supplied _by the application deployment_.
This way, you still have to deal with the exporter's configuration, but it is part of the application code, and tied into the application development cycle. You make changes in one repository, and the timing of the rollout is naturally coordinated by your deployment mechanism.

**Comment by matthiasr** [comment]
I'll close this issue. With the new relay feature, transitioning to the exporter as a sidecar is even easier. I think client-driven configuration opens a big can of worms that I want to avoid, and by treating exporter configuration on par with application code, you can get the same effect.
