### ISSUE TITLE
Summary Max Age behaves unexpectedly.

### ISSUE THREAD

**Issue by hb0nes** [prometheus/statsd_exporter#316]
I have a Python script that sends data 4 times a second to statsd_exporter.
When I change the max summary age to 15s, I expect the 0.99 or 0.999 quantile to change every 15 seconds at least to something higher, or lower. Sometimes these quantiles (when graphed) just flatline for minutes on end, with exactly the same value. That is not expected behaviour.

Therefore, in its present state, statsd_exporter is deemed unreliable for measuring outliers during latency measurements. 

If I somehow misinterpreted the summary_max_age variable - the docs should at the very least be updated to better reflect what it truly does.

**Comment by matthiasr** [comment]
At 4 samples per second, and 15 seconds, you have accumulated 60 samples in total. The 0.999 quantile is defined as the value where one in 1000 samples have a higher value. This is simply not a calculation that will work over only 60 samples.

**Comment by matthiasr** [comment]
the max age is directly passed through to the client library, so the relevant documentation is [here](https://pkg.go.dev/github.com/prometheus/client_golang@v1.6.0/prometheus?tab=doc). I would be happy to accept a PR that mentions this.

**Comment by hb0nes** [comment]
> At 4 samples per second, and 15 seconds, you have accumulated 60 samples in total. The 0.999 quantile is defined as the value where one in 1000 samples have a higher value. This is simply not a calculation that will work over only 60 samples.

You're right, we were just looking for a way to find a maximum value for those 60 samples (as in max(samples[1m]).
