### ISSUE TITLE
Bug (maybe): Capture group match (regex) converts only one metric type

### ISSUE THREAD

**Issue by audip** [prometheus/statsd_exporter#322]
## What happened?

Only one metric type is translated from statsd to prometheus when a regex pattern is specified. Bug is that it only converts one and it should have converted all metric types that are captured by a regex pattern.

```
prod-app-challenge-daemon.gg.consumer.challenge-daemon.mfp.exercise_entry_created.in-flight-time:70490531|ms
prod-app-challenge-daemon.gg.consumer.challenge-daemon.mfp.exercise_entry_created.payload-decoded:1|c
```

This is the output that I saw:
```
gg_consumer{topic="exercise_entry_created",type="payload-decoded",zone="mfp"} 1
```

## What did I expect to happen?
When a metric mapping is added to capture a group, it should pick up both counters and timers instead of requiring two separate mappings (with likely separate metric name)

```
mappings:
- match: prod-app-challenge-daemon\.gg\.([\w-]+).challenge-daemon\.([\w-]+)\.([\w_]+)\.([\w-]+)
  match_type: regex
  name: "gg_consumer"
  labels:
    zone: "$2"
    topic: "$3"
    type: "$4"
```

With this mapping, I would have expected both `in-flight-time` to have been translated to prometheus summary/histogram and `payload-decoded` to have been translated to prometheus counter. It actually converted just one. This is what I expected to see:

```
gg_consumer{status="event-received"} 1
gg_consumer{topic="exercise_entry_created",type="payload-decoded",zone="mfp"} 1
gg_consumer{topic="exercise_entry_created",type="in-flight-time",zone="mfp",quantile="0.5"} 70490.531
gg_consumer{topic="exercise_entry_created",type="in-flight-time",zone="mfp",quantile="0.9"} 70490.531
gg_consumer{topic="exercise_entry_created",type="in-flight-time",zone="mfp",quantile="0.99"} 70490.531
gg_consumer_sum{topic="exercise_entry_created",type="in-flight-time",zone="mfp"} 70490.531
gg_consumer_count{topic="exercise_entry_created",type="in-flight-time",zone="mfp"} 1
```

Either I am doing something wrong in the mapping configuration or the behavior is to translate only one metric type for a regex pattern (which should be enhanced to translate all the different metric types captured by a regex)

## Any additional information:

At work, we have an in-house tool to test out statsd-exporter configuration, here's the output from the translations

![image](https://user-images.githubusercontent.com/4290846/86880897-40a4d280-c0a2-11ea-8b0b-6fa8cba3e2d6.png)

**Comment by matthiasr** [comment]
Prometheus only supports one metric type for a given metric name. In the example you gave, you would need multiple conflicting TYPE declarations, which is not allowed. In the current iteration of the exposition format, the different time series that make up e.g. a summary may look like they are separate time series, but conceptually they form one compound sample.

You should be able to match more than one type in one mapping, as long as they map to different names.

Thank you very much for the detailed report (any chance you might open source that mapping config tester? 😄), unfortunately having multiple types under the same metric name is not something we can support.
