### ISSUE TITLE
Registry as an interface?

### ISSUE THREAD

**Issue by bakins** [prometheus/statsd_exporter#330]
I want to embed statsd_exporter in another project rather than copy-paste large portions of it.  I do not want to use the default prometheus registery.  Thoughts on the Registry type used by Exporter being an interface?  It'd have a more functions than I normally like to have for an interface, but not too terrible.   The current registry implementation would be the only supported/in-tree implementation.

I can do a PR if you think the idea is acceptable.

**Comment by matthiasr** [comment]
Yes please, this is perfectly in line with my thoughts on splitting the exporter up into reusable packages and re-using them in other places. The next use case I have in mind is the Graphite exporter.
