### ISSUE TITLE
Missing support for default summary and histogram options

### ISSUE THREAD

**Issue by bseabra** [prometheus/statsd_exporter#336]
I'm able to configure default values for quantiles in the configuration file under `defaults`. However, `max_summary_age` and `summary_age_buckets` seem to be only defined within `mappings` for a specific metric. Is there a way to define these 2 parameters globally, for all metrics?

**Comment by matthiasr** [comment]
You are right, [SummaryOptions and HistogramOptions](https://github.com/prometheus/statsd_exporter/blob/da85f9d20753bfa5d7f43f24b9b126af906e4390/pkg/mapper/mapping.go#L42-L43) are missing from the [defaults struct](https://github.com/prometheus/statsd_exporter/blob/da85f9d20753bfa5d7f43f24b9b126af906e4390/pkg/mapper/mapper_defaults.go#L18-L26) (and then probably need to be handled when the defaults are applied).
