### ISSUE TITLE
Support "API keys" to ensure metric authenticity

### ISSUE THREAD

**Issue by yaron-idan** [prometheus/statsd_exporter#337]
Would it be possible to add support for a key prefix that would serve as an authentication method for incoming metrics? We've been using this with [Hosted Graphite Statsd](https://www.hostedgraphite.com/docs/integrationguide/ig_hosted_statsd.html#sending-a-statsd-metric) offering and it seems to be a useful way of making sure all metrics reaching statsd are sent from a trusted endpoint.

**Comment by matthiasr** [comment]
I believe you can already do this – add metric mappings that include this prefix, and finally add a "drop" action for everything else as in [this example](https://github.com/prometheus/statsd_exporter#drop-action). Is that good enough?

**Comment by yaron-idan** [comment]
Yeah, that sounds greeat. I'll give it a try and close the issue if it will suffice. Thanks!
