### ISSUE TITLE
Add isAlive endpoint for k8s deployments

### ISSUE THREAD

**Issue by yaron-idan** [prometheus/statsd_exporter#338]
I'm deploying the exporter in our k8s cluster using this [chart](https://github.com/niclic/helm-charts/tree/master/prometheus-statsd-exporter), which probes the `/metrics` to make sure the exporter is alive.

I would rather use a dedicated `/isAlive` endpoint for this matter, any objections for adding one?
If this seems like a good idea, I might be able to create a small PR to add that.

**Comment by matthiasr** [comment]
Please use the same endpoints as the [Prometheus management API](https://prometheus.io/docs/prometheus/latest/management_api/) for consistency.

**Comment by matthiasr** [comment]
Fixed in #339
