### ISSUE TITLE
statsd_exporter OOM (out of memory)

### ISSUE THREAD

**Issue by Vytiss** [prometheus/statsd_exporter#342]
Hello,

we are facing issues with our prometheus statsd_exporter in openshift pod running out of memory. We have pod limit set to 2,5GB of RAM, in 30 days it reached that limit and died(OOM). It crashed one month ago and again, yesterday. 

We are getting same amount of metric daily/weekly/monthly, we don't get any spikes or increased load, so we are not sure what is happening, why the memory keep increasing that fast. 

We have tried to simulate the OOM, running load/stress test and based on script below, the memory usage seems to be increasing too high too fast

Any advise, what might be the reason, why statsd_exporter is eating all the memory?

Metrics for statsd_exporter in openshift pod that we use in Production:

![image](https://user-images.githubusercontent.com/5333136/96604146-71311500-12fd-11eb-86cf-d831228d44da.png)

Script we used to try OOM the statsd_exporter that we run locally in kubernetes:

```
#!/bin/bash
function send()
{
    while true; do
        number=$(( $RANDOM % 128 + 16 ))
        tag=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $number | head -n 1`
        tag2=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $number | head -n 1`
        echo -e "test.metric,tag=$tag:+$number|c\ntest.timing,$tag=$tag2:$number|ms" >/dev/udp/127.0.0.1/9125
        echo -e "test.metric,tag=lag:+1|c" >/dev/udp/127.0.0.1/9125
    done;
}
function spawn() {
    for i in {1..10}
    do
        send&
        echo spawning;
    done
    echo "spawn done"
    sleep 1;
}

for z in {1..10}
do
    spawn;
    echo "HERE WE GO AGAIN!"
done;
while true; do sleep 1; done;

```
And the memory is increasing very fast, though we expect it to be flat. So similar behaviour we see in metrics above with our pod in openshift that is serving our application metrics and in our test kubernetes environment that we tested using our stress script

![problem](https://user-images.githubusercontent.com/5333136/96604577-f1f01100-12fd-11eb-9115-36f8f8ea9d1f.gif)

**Comment by matthiasr** [comment]
That's interesting, can you get a [heap profile](https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/) or two? (ideally one early and one late, so we can see the difference).

**Comment by Vytiss** [comment]
@matthiasr would you be able to guide a little bit, how to get this heap profile as we are not familiar with Go? As i understand, i need to attach the http listener, that would let me get to /debug/pprof path, but how should i attach it to the udp listener? I was able to add http listener with port 8080, but it doesnt show anything interesting as it doesnt get any traffic through it. And i need to monitor and get stats for udp endpoint which we use to ship metrics to statsd. So it's not clear, what changes to stats_exporter main.go file should i add to get heap dump. Any guidance would be appreciated

**Comment by Vytiss** [comment]
Seems like i have managed to make the heap dumps. Please find attached. 


pprof.statsd_exporter.alloc_objects.alloc_space.inuse_objects.inuse_space.004_without_load.pb is without stress.sh started, so no traffic to udp port. The remaining ones were captured during stress.sh script running all the time. I did those after ~5 minutes each one

[pprof.statsd_exporter.alloc_objects.alloc_space.inuse_objects.inuse_space.004_without_load.pb.gz](https://github.com/prometheus/statsd_exporter/files/5422152/pprof.statsd_exporter.alloc_objects.alloc_space.inuse_objects.inuse_space.004_without_load.pb.gz)
[pprof.statsd_exporter.alloc_objects.alloc_space.inuse_objects.inuse_space.006.pb.gz](https://github.com/prometheus/statsd_exporter/files/5422153/pprof.statsd_exporter.alloc_objects.alloc_space.inuse_objects.inuse_space.006.pb.gz)
[pprof.statsd_exporter.alloc_objects.alloc_space.inuse_objects.inuse_space.005.pb.gz](https://github.com/prometheus/statsd_exporter/files/5422154/pprof.statsd_exporter.alloc_objects.alloc_space.inuse_objects.inuse_space.005.pb.gz)
[pprof.statsd_exporter.alloc_objects.alloc_space.inuse_objects.inuse_space.007.pb.gz](https://github.com/prometheus/statsd_exporter/files/5422155/pprof.statsd_exporter.alloc_objects.alloc_space.inuse_objects.inuse_space.007.pb.gz)
[pprof.statsd_exporter.alloc_objects.alloc_space.inuse_objects.inuse_space.008.pb.gz](https://github.com/prometheus/statsd_exporter/files/5422160/pprof.statsd_exporter.alloc_objects.alloc_space.inuse_objects.inuse_space.008.pb.gz)

**Comment by Vytiss** [comment]
@matthiasr did you have a chance to look at it? Thanks

**Comment by glightfoot** [comment]
It looks like you are creating lots of new metrics since the label key is random. Since each metric is the combination of metric name and label keys/values, lots of summary objects are created, which consume all the space. This is expected, and should be fixed by removing cardinality from the labels.

Can you confirm if there is unbounded cardinality in the labels of your production instance?

You can view the pprof with the following command:
```
go tool pprof -web pprof.statsd_exporter.alloc_objects.alloc_space.inuse_objects.inuse_space.009.pb
```

**Comment by matthiasr** [comment]
Thank you @glightfoot for looking into it. Sending an unbounded set of metrics will indeed result in unbounded memory use – there isn't really anything we can do about that, sorry 😄
