### ISSUE TITLE
Any configuration option to turn off aggregations on statsd timers ?

### ISSUE THREAD

**Issue by rahulravindran0108** [prometheus/statsd_exporter#348]
I'm trying to hook statsite as an upstream service from which
the exporter receives statsistics. For now, I want to relay the
metrics as is to prometheus without aggregating the timers in
statsd format. Is it possible to do this ?

**Comment by matthiasr** [comment]
No, this is not possible – the semantics are incompatible. Statsd timers are a series of observations – "this request took that long". Prometheus does not deal in events, only metrics, so it needs a pre-aggregation. In native Prometheus instrumentation, this pre-aggregation happens in-process; in this case it happens in the exporter, but you cannot turn it off.

If something has already pre-aggregated, it should send the results as a gauge – only for gauges do the semantics match, and consequently the exporter passes them through unchanged.
