### ISSUE TITLE
Buffer for reading udp packets is too small.

### ISSUE THREAD

**Issue by TursMA** [prometheus/statsd_exporter#35]
512 bytes are ok for the wild Internet. For local network we can send udp packets up to 1432 bytes or greater. For example it's very important if we use buffered client (github.com/cactus/go-statsd-client/statsd/client_buffered.go). So I suggest increasing buf size to 2-8k. 
Also MTU is important for client. Udp packet can be split or dropped by ISP because of size. Server shouldn't evaluate MTU. 

{code}
func (l *StatsDListener) Listen(e chan<- Events) {
    // TODO: evaluate proper size according to MTU
    var buf [512]byte
    for {
        n, _, err := l.conn.ReadFromUDP(buf[0:])
        if err != nil {
            log.Fatal(err)
        }
        l.handlePacket(buf[0:n], e)
    }
}
{code}

**Comment by juliusv** [comment]
You're right, that should definitely be increased and the comment doesn't make too much sense. No idea why it was *that* low in the first place!

See https://github.com/prometheus/statsd_exporter/pull/36

**Comment by TursMA** [comment]
Thank you very much!

**Comment by SuperQ** [comment]
The docs default the max size to 512b[0] for "open internet" safety concerns.  But this can be configured by the admin.

This may be something we want to have as a runtime flag if possible.

[0]: http://statsd.readthedocs.io/en/v3.1/configure.html#runtime

**Comment by TursMA** [comment]
Flag is overhead, I think.
Max UPD packet size is (65,535 − 8 byte UDP header − 20 byte IP header)
For message-based sockets, such as SOCK_DGRAM and SOCK_SEQPACKET, the entire message shall be read in a single operation.
So buffer[65,535] covers all possible cases. We allocate it just once, so fix is changing buffer to max allowable size. =)

**Comment by SuperQ** [comment]
Yea, that seems reasonable.
