### ISSUE TITLE
License Issue for github.com/hashicorp/golang-lru

### ISSUE THREAD

**Issue by zhiyingl** [prometheus/statsd_exporter#362]
github.com/hashicorp/golang-lru has a Mozilla license, which is different from that of github.com/prometheus/statsd_exporter. 

The difference (and the mere presence of the former) makes it more difficult for open-source projects (e.g., https://fuchsia.dev) to vendor the latter.

License: MPL-2.0 license
More details at: https://raw.githubusercontent.com/spdx/license-list/master/MPL-2.0.txt

**Comment by matthiasr** [comment]
Interesting, I can see how that can be problematic. Do you have a suggested replacement?

**Comment by glightfoot** [comment]
I think this might work https://github.com/karlseguin/ccache

**Comment by zhiyingl** [comment]
github.com/golang/groupcache should work, which is used by opencensus-go lib.

https://github.com/census-instrumentation/opencensus-go/commit/59d1ce35d30f3c25ba762169da2a37eab6ffa041

**Comment by glightfoot** [comment]
Note that hashicorps lru cache is a thread-safe version of the groupcache lru cache, which is not.

**Comment by matthiasr** [comment]
I like https://github.com/karlseguin/ccache – it also supports TTLs per item so we could integrate that with the metric expiration.

**Comment by matthiasr** [comment]
Keeping this open as we still depend on the MPL-licensed LRU implementation, but the dependency is now more contained within the mappercache package.

**Comment by matthiasr** [comment]
We no longer depend on golang-lru!
