### ISSUE TITLE
Question around throughput

### ISSUE THREAD

**Issue by jordangarside** [prometheus/statsd_exporter#377]
Hi there 👋 ,

I'm trying to send out a bunch of timings through the exporter.

I'm running the latest version (`0.20.2`) like so:
```bash
./statsd_exporter-0.20.2.linux-amd64/statsd_exporter \
  --statsd.listen-unixgram=/tmp/statsd.sock \
  --statsd.read-buffer=120000
```

I have a fairly simple Rust program that looks like this:
```rs
use cadence::prelude::*;
use cadence::{BufferedUnixMetricSink, StatsdClient};
use rand::Rng;
use std::os::unix::net::UnixDatagram;

fn main() {
    let socket = UnixDatagram::unbound().unwrap();
    socket.set_nonblocking(false).unwrap();
    let sink = BufferedUnixMetricSink::from("/tmp/statsd.sock", socket);
    let client = StatsdClient::from_sink("example", sink);

    let mut rng = rand::thread_rng();

    loop {
        let n1: u8 = rng.gen();
        client.time("hello.there", u64::from(n1)).ok();
    }
}
```

This is running on a 96 vCPU AWS instance, but I'm capping out at around ~360k timings per second (as measured by the increase in `example_hello_there_count` on the `/metrics` endpoint per second).

The exporter is spinning up 48 threads:
```bash
# ps -o nlwp $(pgrep statsd_exporter)
NLWP
  48
```

But it appears it's actually only taking advantage of ~2.5 cores while the rust program is running against it (and the rust program `tmp` is sitting at ~35%):
![image](https://user-images.githubusercontent.com/6321824/118354547-626fb100-b520-11eb-9e81-658bf6852296.png)

Also, things don't improve if I run additional processes of the rust program:
![image](https://user-images.githubusercontent.com/6321824/118354646-df9b2600-b520-11eb-903b-3c4e6f4203d2.png)

In practice I'm trying to be able to export ~3 million timings per second through the exporter.

Am I doing something totally wrong here?

Thanks!

**Comment by SuperQ** [comment]
The packet reader off the socket is likely only going to be able to use one core, as it's a single goroutine.

In a normal production practice, the `statsd_exporter` is deployed in a distributed way. Each node, or in Kubernetes-style depoyments each pod, has a statsd_exporter. This allows things to be scaled better.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

**Comment by jordangarside** [comment]
Will do thanks! 👍

**Comment by jordangarside** [comment]
For anyone interested, I posted the [question on discourse](https://discuss.prometheus.io/t/scaling-statsd-exporter-throughput-on-a-single-host/226).
