### ISSUE TITLE
level.Debug(logger).Log(...) is too expensive

### ISSUE THREAD

**Issue by royeo** [prometheus/statsd_exporter#384]
```go
func (l *StatsDUnixgramListener) HandlePacket(packet []byte) {
	l.UnixgramPackets.Inc()
	lines := strings.Split(string(packet), "\n")
	for _, line := range lines {
                // it is too expensive
		level.Debug(l.Logger).Log("msg", "Incoming line", "proto", "unixgram", "line", line)
		l.LinesReceived.Inc()
		l.EventHandler.Queue(l.LineParser.LineToEvents(line, l.SampleErrors, l.SamplesReceived, l.TagErrors, l.TagsReceived, l.Logger))
	}
}
```

level.Debug(logger).Log("...")  will always call `runtime.Caller`，`runtime.Caller` is too expensive，It affects overall performance.

**Comment by SuperQ** [comment]
Can you provide benchmark data on what "too expensive" means in terms of real numbers?

**Comment by royeo** [comment]
![image](https://user-images.githubusercontent.com/24458434/128491407-d7f0caa3-d9f2-4c5c-b253-765a7313c036.png)

This is cpu flame graph.

**Comment by SuperQ** [comment]
Seems like an upstream bug to file with https://github.com/go-kit/log.

**Comment by matthiasr** [comment]
I agree in principle, logging ought to be cheap. In practice, since it isn't and this is in the very hot path, we can work around it by making the call itself conditional. There should be a way to get the current log level? @royeo do you want to make a PR for that?

**Comment by royeo** [comment]
We can add a flag that specifies whether to add the `caller` field, how about this change ?

**Comment by matthiasr** [comment]
I don't want to introduce too many options if we can avoid it. Can we
unconditionally remove the caller just from this one call?

**Comment by royeo** [comment]
Instead of using `promlog.New`, I think we can new a  log.logger without caller

```go
promlogConfig := &promlog.Config{}
flag.AddFlags(kingpin.CommandLine, promlogConfig)
kingpin.Version(version.Print("statsd_exporter"))
kingpin.HelpFlag.Short('h')
kingpin.Parse()
// logger := promlog.New(promlogConfig)  
logger := newLogger(promlogConfig) // without caller and ts field
```

**Comment by matthiasr** [comment]
I think time is important. I don't want to remove caller overall, only for this super hot call. I think we can do that inline, like

```
level.Debug(log.With(logger, "caller", "unavailable")).…
```

or something like that. It's not clear to me whether we need a function there that implements `log.Valuer` or whether a fixed string works.

The alternative that would be even cheaper if debug logging is disabled (i.e. we don't need the whole line computed to begin with) is to extract or pass the value of the log level flag, and then

```go
if debug {
  level.Debug(logger).…
}
```

it's not pretty, and I think the upstream level package should work that way, but it doesn't.

**Comment by royeo** [comment]
if we do as `level.Debug(log.With(logger, "caller", "unavailable"))`,  there will still be some hot calls like `runtime.newobject` or  `runtime.growslice`. So for this hot call, it might be better to just determine the log level and filter it.

**Comment by royeo** [comment]
How about this PR #385 ? @matthiasr @SuperQ
