### ISSUE TITLE
Decrementing counters doesn't work

### ISSUE THREAD

**Issue by mamercad** [prometheus/statsd_exporter#394]
I'm running the latest (as of 6d ago) image, and it doesn't seem like decrementing counters works:

```bash
❯ curl -s localhost:9102/metrics | grep my_coun
# HELP my_counter Metric autogenerated by statsd_exporter.
# TYPE my_counter counter
my_counter 13

❯ echo "my_counter:1|c" | nc -v localhost 9125
Connection to localhost port 9125 [tcp/*] succeeded!

❮ curl -s localhost:9102/metrics | grep my_coun
# HELP my_counter Metric autogenerated by statsd_exporter.
# TYPE my_counter counter
my_counter 14

❯ echo "my_counter:-1|c" | nc -v localhost 9125
Connection to localhost port 9125 [tcp/*] succeeded!

❮ curl -s localhost:9102/metrics | grep my_coun
# HELP my_counter Metric autogenerated by statsd_exporter.
# TYPE my_counter counter
my_counter 14
```

**Comment by glightfoot** [comment]
Counters can only be incremented. You would need to use a gauge if you want to increment and decrement.

**Comment by mamercad** [comment]
> Counters can only be incremented. You would need to use a gauge if you want to increment and decrement.

I thought this as well, do you have a reference that mentions this by chance? I don't really see that stated [here](https://github.com/statsd/statsd/blob/master/docs/metric_types.md). And, there are third-party StatsD client libraries which support decrementing counters, like [this](https://statsd.readthedocs.io/en/v3.2.1/types.html#counter-type).

**Comment by glightfoot** [comment]
The statsd side lacks a concrete standard, but the Prometheus side is very clear and limits the behavior of the statsd-exporter https://prometheus.io/docs/concepts/metric_types/

**Comment by SuperQ** [comment]
I ran into this the other day when reading a statsd python implementation. I couldn't believe that it implemented a decrement for a counter. Decrement operator on counters is nonsensical.

I guess we need to clarify the documentation that this is explicitly not supported.

**Comment by mamercad** [comment]
Ah, thank you very much (I should have looked at the Prometheus documentation)!

**Comment by matthiasr** [comment]
This is a not necessarily obvious limitation of the StatsD-Prometheus model translation. Would it be worth calling out in the readme?
