### ISSUE TITLE
Is this project truly a "drop-in replacement for StatsD"?

### ISSUE THREAD

**Issue by chainhead** [prometheus/statsd_exporter#420]
The overview section says,
> The StatsD exporter is a drop-in replacement for StatsD.

The term **drop-in** sounds like I can uninstall StatsD and install the exporter so that, I am able to expose a Prometheus metrics end-point over and above what StatsD provides. Here is the Before and After scenario.

**Before**

StatsD 

- ingests metrics from application
- writes to back-ends

**After**

`statsd_exporter`

- ingests metrics from application
- writes to back-ends
- translates metrics to Prometheus format
- Exposes a metrics end-point for Prometheus server to scrape.

However, the scenarios mentioned in the `README.md` file rely on the existing StatsD daemon.

**Comment by SuperQ** [comment]
The statsd relay is an optional feature to allow users to transition from an existing system. This allows users to have both an old statsd data sink and Prometheus at the same time.

**Comment by matthiasr** [comment]
The exporter is "drop-in" in the sense that you do not need to reinstrument all your software. Is there is a generally accepted definition of the term that you can point us to? What alternative formulation do you propose?

**Comment by chainhead** [comment]
> What alternative formulation do you propose?

This.

> Uninstall StatsD and install the exporter so that, I am able to expose a Prometheus metrics end-point over and above what StatsD provides.

**Comment by matthiasr** [comment]
Is that a description of what the exporter does, or what you would like it to do? On the receive side, I want the exporter to be fully compatible with all statsd implementations (insofar as they do not conflict), but it will never implement what statsd itself does, i.e. writing to Graphite.
