### ISSUE TITLE
Match metric by value

### ISSUE THREAD

**Issue by husam212** [prometheus/statsd_exporter#425]
Is there a way to configure mappings to match a metric by name and value, for example I want to drop a metric when its value goes zero.

**Comment by matthiasr** [comment]
Hi, thank you for the idea. There is currently no way to do this, but I also don't want to add it. It is out of scope for the exporter, and fits neither the statsd nor the Prometheus data model cleanly.

The mapping configuration is meant to translate between the statsd and Prometheus data models, not as a generalized metric processing language. Consider https://vector.dev if that is what you need.
