### ISSUE TITLE
New metric for relay lines total

### ISSUE THREAD

**Issue by pedro-stanaka** [prometheus/statsd_exporter#427]
I wanted to compare how many lines are being ingested by statsd_exporter and how many lines are being forwarded (except for long lines), but it seems like currently we do not have a metric for how many lines we are relaying. I would expect an increment here: https://github.com/prometheus/statsd_exporter/blob/master/pkg/relay/relay.go#L138-L155. 

I was wondering if I am missing something, and if not, can we add this new metric. I would be inclined to contribute, but wanted to hear from the maintainers first.

**Comment by matthiasr** [comment]
Yes, that's a good idea! I would be happy to have this 😃

**Comment by matthiasr** [comment]
Done in #434
