### ISSUE TITLE
healthcheck endpoint

### ISSUE THREAD

**Issue by shorinji** [prometheus/statsd_exporter#437]
Any plans to add healthcheck endpoints, like liveness and readiness that k8s uses?

Feel free to tell me that I am doing things the wrong way.

**Comment by pedro-stanaka** [comment]
You can use `/-/healthy` and `/-/ready` just like in Prometheus.

**Comment by matthiasr** [comment]
Thank you @pedro-stanaka – indeed, we already implement these.
