### ISSUE TITLE
[docs] Document using regex to mark the original metric name as label

### ISSUE THREAD

**Issue by pedro-stanaka** [prometheus/statsd_exporter#438]
### Problem and feature request

I am in need to build a custom UI that pairs the original statsd metric name which people are sending from applications with the names they see in Prometheus/Grafana. Since undoing the process of translating metric names is not-trivial (not to say almost impossible) due to how open metric naming is on statsd-sphere I would like to have a possibility to have metrics tagged with their original names before translation.

### Solution proposal

We could introduce a feature flag (or some cli argument) that enables such feature and in the `github.com/prometheus/statsd_exporter/pkg/mapper/MetricMapper` we could tag the final metric with a label `original_name`.

**Comment by matthiasr** [comment]
Sorry for the long silence, I had to think about and test this out, and then forgot about it.

I found that this _is_ already possible, in a very general way using `$0` in the mapping config, but only if you are using the `regex` match type. It must have been possible with glob matching when that was translated to regular expressions, but in the reimplementation as a state machine, we lost this.

Rather than hard-coding a label, I would prefer if we fix the use of `$0` as a substitution:

```yaml
# tmp/mapping.yml
mappings:
- match: "glob.*"
  name: "test_globbed"
  labels:
    part: "$1"
    whole: "$0"
- match: "re\\.([^.]*)"
  name: "test_regex"
  match_type: regex
  labels:
    part: "$1"
    whole: "$0"
```

```console
$ ./statsd_exporter --log.level debug  --statsd.mapping-config tmp/mapping.yml &
level=info ts=2022-06-18T10:29:47.002Z caller=main.go:291 msg="Starting StatsD -> Prometheus Exporter" version="(version=, branch=, revision=)"
level=info ts=2022-06-18T10:29:47.002Z caller=main.go:292 msg="Build context" context="(go=go1.18.2, user=, date=)"
level=info ts=2022-06-18T10:29:47.003Z caller=main.go:341 msg="Accepting StatsD Traffic" udp=:9125 tcp=:9125 unixgram=
level=info ts=2022-06-18T10:29:47.003Z caller=main.go:342 msg="Accepting Prometheus Requests" addr=:9102
$ echo 'glob.one:1|c' | nc localhost 9125
level=debug ts=2022-06-18T10:29:56.193Z caller=listener.go:136 msg="Incoming line" proto=tcp line=glob.one:1|c
$ echo 're.one:1|c' | nc localhost 9125
level=debug ts=2022-06-18T10:30:02.809Z caller=listener.go:136 msg="Incoming line" proto=tcp line=re.one:1|c
$ curl -s http://localhost:9102/metrics | fgrep test_
# HELP test_globbed Metric autogenerated by statsd_exporter.
# TYPE test_globbed counter
test_globbed{part="one",whole=""} 1
# HELP test_regex Metric autogenerated by statsd_exporter.
# TYPE test_regex counter
test_regex{part="one",whole="re.one"} 1
```

We should, of course, also document it. Is this something you would like to tackle?

**Comment by pedro-stanaka** [comment]
I can document this in the README for sure. I will put up a PR during this week. 👍 I will test on my side first and make sure it is working with my use-case.

**Comment by pedro-stanaka** [comment]
So, this sadly won't work for me. I am working with tens of thousands of metrics and it is not possible to configure a regex for each of them. From what I see in the code we can't create a mapping without a name (also wouldn't be called a mapping then 🤣 ). I will patch on the client side so we send the metric name as a statsd label.
