### ISSUE TITLE
Add configuration for how long gauge metrics are stored

### ISSUE THREAD

**Issue by NotVeryWellF** [prometheus/statsd_exporter#452]
It would be great if we could configure statsd-exporter not to store gauge metrics after the specific time from last recieved metric by the labels. For example, `--statsd.store-gauge-metrics-time=1200`, after 20 minutes statsd-exporter will not store last received gauge value.

**Comment by NotVeryWellF** [comment]
Sorry, `TTL` exists  😅

**Comment by Upanshu11** [comment]
How to make sure TTL works only for specific metrics/labels, and not all?

**Comment by matthiasr** [comment]
You can set the `ttl:` parameter on any match, and it will override the global default, like in [this test example](https://github.com/prometheus/statsd_exporter/blob/871e2d8df1da51d4eed27738f4bc079271a09c61/pkg/exporter/exporter_test.go#L957-L962).
