### ISSUE TITLE
Capture hostname of event generator and expose to Prometheus as label 

### ISSUE THREAD

**Issue by UserNoOne** [prometheus/statsd_exporter#467]
is it possible to export hostname of client so that it will be helpful when monitoring metrics at Grafana/Prometheus end. 

As of now when I send event from statsd client. It is showing something like this in Prometheus
`sample{instance="statsd:9109", job="prometheus"}` 

Instead would like to see as below
`sample{instance="statsd:9109", job="prometheus",source="10.12.3.4"}`

here 10.12.3.4 is the source IP of statsd client

**Comment by matthiasr** [comment]
This is not directly possible at the moment and I do not want to add it. Statsd doesn't, so this would be strictly beyond the scope of translating between the metric formats. Additionally, adding either the hostname or the IP is a relatively narrow piece of information that works for you but is not always what one needs.

If you need the metrics on a by-source basis, it is best to run the exporter as a sidecar – one exporter directly on each source node, or in the pod uf you are on Kubernetes. This way the exporter metrics endpoint becomes a stand-in for native instrumentation. To the outside observer (Prometheus) it becomes indistinguishable from native instrumentation. You can even manage the mapping as part of the application code. And, most relevant to this request, you get the full power of Prometheus service discovery and relabeling to add source-specific metadata as labels.

I hope this clarifies things!
