### ISSUE TITLE
Published DockerHub tag has changed

### ISSUE THREAD

**Issue by bendemaree** [prometheus/statsd_exporter#47]
The default tag for Docker images is `latest` but a new tag went up under `master` on [DockerHub](https://hub.docker.com/r/prom/statsd-exporter/tags/). This means the `pull` command fails:

```
$ docker pull prom/statsd-exporter
Using default tag: latest
Pulling repository docker.io/prom/statsd-exporter
Tag latest not found in repository docker.io/prom/statsd-exporter
```

One must now run `docker pull prom/statsd-exporter:master` instead.

It would be lovely to have it published under the `latest` tag again as it would otherwise mean a lot of config file updates. Thanks!

**Comment by sdurrheimer** [comment]
Looks like the previous hub repo has been deleted and recreated as a non-automated build, losing old tags at the same time, sorry about that.

Some exporters didn't follow our way of doing image's tags like you can see with Prometheus or Alertmanager. The master branch shouldn't be considered as `latest`.

We have recently merged a new release process. The `master` branch will be the `master` tag. Only the latest release will be tag as `latest`. A new release is under way, it should be ready soon enough #45.

**Comment by sdurrheimer** [comment]
I have pushed the `master` tag as `latest` to save you time, but keep in mind that this tag will no follow the `master` branch once we will release `statsd-exporter 0.3.0`.

**Comment by bendemaree** [comment]
@sdurrheimer Thank you! I plan to pin a version now that they're available. Appreciate your quick work.
