### ISSUE TITLE
Can script be run add or transform a field.

### ISSUE THREAD

**Issue by hackeraks** [prometheus/statsd_exporter#494]
I am trying to add a field based on existing field in the metric, In order to get the customer name mapped to an id, this id is present in the metric, I need to add a label with value of fetched result. 

- match: "web\\.service\\.action\\.(.*)\\.token_(.*)\\.uri_(.*)\\.type_(.*)\\.total_hits"
        match_type: regex
        name: "webservice"
        timer_type: "histogram"
        labels:
          field1: "$1"
          id: "$2"
          name: $(run my script to fetch value)
          p: "$3"
          v: "$4"

Any pointer or suggestion.
Thanks!

**Comment by matthiasr** [comment]
Hi, no, this is not something we can or will support. Ingesting statsd events is a high-frequency low-latency operation, we deliberately do not support anything that can take unbounded time in these mappings.

I would suggest to have a _separate_ metric for this mapping, either as a custom exporter, or as a generated set of recording rules, like

```
customer_info{id="id1",name="Customer Name 1"} 1
customer_info{id="id2",name="Customer Name 2"} 2
```

Then you can join these metrics at query time, for those cases where you actually need the customer name.

With a custom exporter, you can hook this up to wherever you keep your customer records, including making HTTP requests. There are many examples for this in whichever language you are most comfortable with.
