### ISSUE TITLE
Issues with exposed metrics

### ISSUE THREAD

**Issue by tcolgate** [prometheus/statsd_exporter#53]
statsd_exporter_packets_total does not count packets. It counts events, and the dimensions are not used consistantly. dogstatsd metrics get double counted as both legal and dogstatsd.

networkStats.WithLabelValues("legal").Inc() should be moved out of the per-line loop.
I can PR this, but the other counters need some thought too, the various forms of invalid should probably be on events (lines), rather than packets.

**Comment by matthiasr** [comment]
This was fixed in #106.
