### ISSUE TITLE
Support for exemplars

### ISSUE THREAD

**Issue by michal-kazmierczak** [prometheus/statsd_exporter#530]
Hello,

I'm a very happy user of the statsd_exporter. 

As the ecosystem grows, recently I've been wondering what would it take to support exemplars as described in the [OpenMetrics spec](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars).

As I'm considering it, it seems to me that it would be a broad scope of changes - starting from an extension in the metric mapping through exporting Prometheus metrics in the OpenMetrics format. 

But before I dig into details I want to ask, has exemplars been already considered?

**Comment by matthiasr** [comment]
I'm not opposed to it, if there is precedent elsewhere in the statsd ecosystem. The scope of this exporter is to provide a translation from the statsd format, it is not meant as a general "push to Prometheus" solution or to define new extensions to the statsd protocol. Which statsd flavor includes something that you would want to translate into exemplars?

**Comment by michal-kazmierczak** [comment]
> Which statsd flavor includes something that you would want to translate into exemplars?

I must admit I haven't found any examples, neither in documentations nor in histograms (final presentations of metrics). 

As I use pure StatsD protocol, I was hoping to see the possibility of adding an extension, but I see your point.

It seems to me that this topic will have to wait until one of the StatsD adaptations uses it. For the time being, I'm fine with closing this issue.
