### ISSUE TITLE
statsd mapping not taking effect

### ISSUE THREAD

**Issue by mg03** [prometheus/statsd_exporter#56]
I get the following metrics wihtout mapping

```
# HELP consul_consul_dns_domain_query_ip_10_113_143_167_ec2_internal Metric autogenerated by statsd_exporter.
# TYPE consul_consul_dns_domain_query_ip_10_113_143_167_ec2_internal summary
consul_consul_dns_domain_query_ip_10_113_143_167_ec2_internal{quantile="0.5"} 1.453363
consul_consul_dns_domain_query_ip_10_113_143_167_ec2_internal{quantile="0.9"} 1.556893
consul_consul_dns_domain_query_ip_10_113_143_167_ec2_internal{quantile="0.99"} 1.556893
consul_consul_dns_domain_query_ip_10_113_143_167_ec2_internal_sum 4.627288
consul_consul_dns_domain_query_ip_10_113_143_167_ec2_internal_count 3
```

I want the metric name like so

```consul_consul_dns_domain_query```

I have a statsd_mmaping.conf like so

```
consul.consul.dns.domain.query.*
name="consul_dns_domain_query"
```

But still the metrics show
```

consul_consul_dns_domain_query_ip_10_113_143_167_ec2_internal{quantile="0.5"} 1.453363
consul_consul_dns_domain_query_ip_10_113_143_167_ec2_internal{quantile="0.9"} 1.556893
consul_consul_dns_domain_query_ip_10_113_143_167_ec2_internal{quantile="0.99"} 1.556893
consul_consul_dns_domain_query_ip_10_113_143_167_ec2_internal_sum 4.627288
consul_consul_dns_domain_query_ip_10_113_143_167_ec2_internal_count 3
```

**Comment by bhourigan** [comment]
You might want to look at this as an alternate approach: https://www.consul.io/docs/agent/options.html#telemetry-disable_hostname

**Comment by mg03** [comment]
@bhourigan : its already set to disable_hostname

these ips are not of the host

For example the leader will do heartbeats with other machines and will put out stats like so

'consul.raft.replication.heartbeat.10.112.79.170:8300': Count: 20 Min: 0.174 Mean: 11.034 Max: 205.667 Stddev: 45.865 Sum: 220.674 LastUpdated: 2017-01-05 22:25:39.475106024 +0000 UTC

'consul.raft.replication.heartbeat.10.112.139.134:8300': Count: 22 Min: 0.652 Mean: 12.734 Max: 109.383 Stddev: 30.426 Sum: 280.146 LastUpdated: 2017-01-05 22:25:39.988548791 +0000 UTC

In the statsd exporter config I have the following:

consul.raft.replication.heartbeat.*.*.*.*
name="consul_raft_replication_heartbeat"
node="${1}.${2}.${3}.${4}"

But still I see entries like 

consul_raft_replication_heartbeat_10_112_119_73_8300{cluster="consul",instance="10.112.82.135",job="consul",quantile="0.99"}

**Comment by matthiasr** [comment]
The mapping had changed a lot since this issue was opened. Is this still a problem?

**Comment by bhourigan** [comment]
No longer an issue - thank you.

**Comment by fruch** [comment]
@matthiasr I still see a similar issue

this is my config:
``` yaml
mappings:
    - match: molotov.*.*.*.*
      name: "molotov_timer"
      labels:
        hostname: "$1"
        method: "$2"
        host: "$3"
        path: "$4"
        job: "molotov"
```

and I see this when calling ` curl 0.0.0.0:9102/metrics | grep mappings`
```bash
statsd_exporter_loaded_mappings 0
...
molotov_rdkucs1_GET_0_0_0_0__search_1_0_0_health{quantile="0.5"} 0
molotov_rdkucs1_GET_0_0_0_0__search_1_0_0_health{quantile="0.9"} 0
molotov_rdkucs1_GET_0_0_0_0__search_1_0_0_health{quantile="0.99"} 0
molotov_rdkucs1_GET_0_0_0_0__search_1_0_0_health_sum 0
molotov_rdkucs1_GET_0_0_0_0__search_1_0_0_health_count 323
```

**Comment by matthiasr** [comment]
So there are no mappings being loaded in the first place? Is there anything in the exporter logs about which configuration it's loading and whether that is successful?

**Comment by fruch** [comment]
I've found the issue to be in the source of my data, someone was rounding the timers to zero. sorry...

**Comment by matthiasr** [comment]
great to hear!
