### ISSUE TITLE
Move from go-kit logger to slog

### ISSUE THREAD

**Issue by pedro-stanaka** [prometheus/statsd_exporter#603]
## Summary

The whole Prometheus ecosystem is moving away from go-kit Logging library towards Go's stdlib slog package. We should also make the move to be in line with what the ecosystem is using. 

See work on Prometheus itself: https://github.com/prometheus/prometheus/pull/14906

Seems like the author of that PR published a helper we can use: `github.com/tjhop/slog-gokit`

**Comment by subrajeet-maharana** [comment]
Can I work on this issue?

**Comment by SuperQ** [comment]
Fixed in https://github.com/prometheus/statsd_exporter/pull/586.
