### ISSUE TITLE
Gauges do not work according to Promethius/Statsd specs

### ISSUE THREAD

**Issue by GentlemanJ** [prometheus/statsd_exporter#64]
Gauges should provide functionality to increase/decrease the metric by the specified value, not just always set the metric to the value. 

For instance;

myGauge:1|g   should set this gauge to 1
myGauge:+1|g should increment the gauge by 1
myGauge:-1|g should decrement the gauge by 1

**Comment by drawks** [comment]
This issue should be marked as resolved with the merge in #65 and the release cut subsequently in #69
