### ISSUE TITLE
initFromString should allow comments in config strings

### ISSUE THREAD

**Issue by shortdudey123** [prometheus/statsd_exporter#67]
**Problem**
It appears that the `initFromFile` for the mapping config file is only read and then passed to `initFromString`.  That method does not appear to have any way to handle comments in the string (or in this specific thought, the mapping file)

**Possible Solution**
Support golang style (`//`) comments in the `initFromString` and ignore them in the case statement in the [`if` statement](https://github.com/prometheus/statsd_exporter/blob/b1f3e6d7be22edabb7d0a49b4fe96a07a1e07c58/mapper.go#L63)

**Comment by drawks** [comment]
Once yaml config files from #66 are merged it seems like the legacy mapper/config format could/should be put out to pasture. yaml allows for comments among many other improvements in how the data is structured.

I've been writing PRs against the branch in #66 for a few days and it is a big improvement.

**Comment by drawks** [comment]
#98 resolves this issue by dropping support for legacy style mapper configs in favor of the yaml configs from #66 which support comments.

**Comment by grobie** [comment]
Thanks!
