### ISSUE TITLE
Allow for dropping unmapped metrics

### ISSUE THREAD

**Issue by drawks** [prometheus/statsd_exporter#77]
The default behavior of passing unmapped metrics through can result in really polluted metric namespaces when using software that generates a large number of dynamic metrics OR a large number of metrics that are irrelevent to the user's interest. I'd like to be able to switch the behavior in the config to blackholing unmapped metrics.

**Comment by robfig** [comment]
FWIW, I'm looking to start up a prometheus installation, and being unable to repeat some but not all from our existing ~100k graphite metrics is sort of a dealbreaker. Thanks for providing this fork, I'll be using it!

**Comment by matthiasr** [comment]
This is fixed by #115. Drop away! Please test from trunk if you're interested in this feature, if there are no issues with it I'm happy to make a release that has it.
