### ISSUE TITLE
Allow for setting "#help" text in mapping config

### ISSUE THREAD

**Issue by drawks** [prometheus/statsd_exporter#78]
The current behavior of providing a help text like 
```# HELP test_case_total Metric autogenerated by statsd_exporter.```

falls pretty far short of the intent of informing the consumer of the metric what the metric represents in easy language. This should be a very small modification that would improve usability.

**Comment by grobie** [comment]
Sounds good! Wanna give it a try and send a PR?

**Comment by drawks** [comment]
Yeah, I'll PR it once #66 is merged, I'd rather let the old mapper configuration format die on the vine and add new mapper features to yaml mapper config

**Comment by drawks** [comment]
This issue is resolved in #87
