### ISSUE TITLE
some common metrics names already in use by exporter

### ISSUE THREAD

**Issue by drawks** [prometheus/statsd_exporter#80]
I'm not sure that I have good proposal to solve this, but I /just/ ran into the issue when mapping some statsd metrics that I cannot define a metric `http_requests_total` because it is already defined by default.

I suppose if an existing metric is redefined by the mapping that the user defined mapping should win out. I'm less sure what to do with the internal telemetry/instrumentation which had originally defined the metric.

**Comment by SuperQ** [comment]
One option, is to move the statsd collected metrics to a separate registry endpoint, say `/statsd`. 
 The `/metrics` endpoint would be just the exporter metrics.

This would make monitoring more complicated as you would need separate jobs for both the statsd metrics and the exporter itself.  But it would eliminate the conflict.

**Comment by matthiasr** [comment]
Are the exporter metrics useful at all? I'm leaning towards just removing them unless someone speaks up for them.

**Comment by SuperQ** [comment]
I like to have exporter metrics, I found them very useful for monitoring memory and cpu use of things like snmp and blackbox exporters.

**Comment by matthiasr** [comment]
Makes sense to have both on separate endpoints then. Since 100% of the users of this exporter need the statsd metrics, and are already using them there, I would prefer to move the exporter metrics to a different endpoint, like `/metrics/internal`.

Do we have examples of this in any other exporter?

**Comment by SuperQ** [comment]
I still suggest `/statsd` as it's a proxy for external data coming in.

**Comment by matthiasr** [comment]
The same argument would apply to all exporters, and everyone would need to configure the same, fixed scrape path in all their configuration. I don't like it to begin with, and I certainly don't like this as the breaking change that it would be.

**Comment by brian-brazil** [comment]
> Do we have examples of this in any other exporter?

Blackbox and snmp have /metrics for their own metrics, and a different endpoint for their special uses.

**Comment by juliusv** [comment]
I think this only applies to exporters where we don't control all exposed metrics (node exporter and others may bridge some that we don't know about, but they are still clearly namespaced as `node_foo_bar_...`). But the Pushgateway would be affected.

**Comment by matthiasr** [comment]
With #233, the `http_requests_total` metric is no longer in use by the exporter. Some other metrics are, if these are an issue for anyone please open a new issue.
