### ISSUE TITLE
Malformed statsd lines should be reported at lower log level.

### ISSUE THREAD

**Issue by drawks** [prometheus/statsd_exporter#81]
```ERRO[0785] Error building event on line docker-lb2.fabio--garbage.tacostand_com./.12_117_14_4_21506.mean:79292673.35|gf: Bad stat type gf  source=exporter.go:51```

Is an example of a badly formed statsd metric for the non-existent type `gf` which raises an `error` level log message from statsd_exporter. This doesn't smell like an error and should probably be downgraded to `info` level. 

https://dave.cheney.net/2015/11/05/lets-talk-about-logging

**Comment by drawks** [comment]
Looking through the code a bit more it seems like there are a bunch of cases of `error` that should be either `info` or even `debug`.

Another arbitrary example: `(counter must be non-negative value)` is another case of an inappropriate metric being received which is dropped. The fact that it is dropped is reflected in the meta-metrics of the exporter itself, the exact cause of the drop /should/ be available when debugging the reason that the drop count has increased. This would typically be accomplished by running the server with logging dialed up to `debug` and debugging the cause.

In `exporter.go` there are 17 places where log lines are emitted at `error`, 1 at `debug` and 0 `info`. This doesn't seem sane to me.

**Comment by SuperQ** [comment]
👍 for both ideas, having internal metrics and reducing these to `DEBUG` level.
