### ISSUE TITLE
client_golang not updated with latest files

### ISSUE THREAD

**Issue by viralkamdar** [prometheus/statsd_exporter#93]
client_golang at https://github.com/prometheus/statsd_exporter/tree/master/vendor/github.com/prometheus/client_golang is not updated with the latest files from https://github.com/prometheus/client_golang
This causes discrepancies in the metrics generated by statsd and prometheus.
The pushgateway floods it's stdout with messages like below
_time="2017-08-30T08:05:00Z" level=warning msg="Metric families 'name:\"go_memstats_sys_bytes\" help:\"Number of bytes obtained by system. Sum of all system allocations.\" type:GAUGE metric:<label:<name:\"instance\" value:\"core-services-ad-level-canary-1654703993-21nr1\" > label:<name:\"job\" value:\"target_9102\" > gauge:<value:1.9605752e+07 > timestamp_ms:1504080298125 > ' and 'name:\"go_memstats_sys_bytes\" help:\"Number of bytes obtained from system.\" type:GAUGE metric:<label:<name:\"instance\" value:\"core-services-host-level-ds-blfqn\" > label:<name:\"job\" value:\"target_9126\" > gauge:<value:1.44943352e+08 > timestamp_ms:1504080291333 > metric:<label:<name:\"instance\" value:\"core-services-host-level-ds-gxkg4\" > label:<name:\"job\" value:\"target_9126\" > gauge:<value:1.83412984e+08 > timestamp_ms:1504080296389 > ' are inconsistent, help and type of the latter will have priority. This is bad. Fix your pushed metrics!" source="diskmetricstore.go:114"_

**Comment by SuperQ** [comment]
Yes, it looks like the vendoring is a bit out of date.
