### ISSUE TITLE
Documentation and real behaviour of metric name mapping not match

### ISSUE THREAD

**Issue by nordicdyno** [prometheus/statsd_exporter#97]
README contains:

> Metrics that don't match any mapping in the configuration file are translated into Prometheus metrics without any labels and with certain characters escaped (_ -> __; - -> __; . -> _)

But in reality metrics with names `metric_name1`, `metric-name2`, `metric.name3` become `metric_name1`, `metric_name2`, `metric_name3` accordingly.

there is the code to reproduce this doc vs reality mismatch https://gist.github.com/nordicdyno/061a50dc29336dc6a60d4d0470edd151

**Comment by matthiasr** [comment]
Is the current real behavior acceptable?

**Comment by matthiasr** [comment]
It seems this has been the case since 728bdc52ae71d9cb9bcbda7d93f47689e94eac4c. I'm not inclined to change the behaviour, I'll fix the documentation instead.
